### ISSUE TITLE
Tapping on QR icon is ignored on Android mobile device in gallery.

### ISSUE THREAD

**Issue by moritzklein** [andreknieriem/photobooth#1]
If I tap on  the QR icon on Android mobile device in gallery, nothing happens. No QR is shown. On PC with chrome QR works just fine!

**Comment by ben9978** [comment]
I have the same problem with iOS. Chrome/Safari/Firefox in macOS work fine.

**Comment by moritzklein** [comment]
You need to edit the ".gal-qr-code" with a touch handler event:

$(document).on('click **touchstart**', '.gal-qr-code', function(e){

**Comment by ben9978** [comment]
Hi Moritz, it is not clear to me where to make this modification. I suspected the .gal-qr-code in style.css. While this changed the appearance of the button, it didn't solve the problem. You don't have the solution in your forked version, do you?

**Comment by moritzklein** [comment]
Hi Ben, no I have the solution on my raspberry :-). I have to push my source to my fork... havn't done it yet. Will try to do it this evening.

**Comment by andreknieriem** [comment]
Fixed now.
