### ISSUE TITLE
Feature request: Trigger photo with external button

### ISSUE THREAD

**Issue by vrs01** [andreknieriem/photobooth#10]
I noticed that some people struggle to press the buttons on a touchscreen, because it needs to be the right length and pressure of the button push.
I would like to attach a physical button that triggers the photo shooting. Either by foot: https://www.amazon.de/KKmoon-Fußschalter-Keyboard-Aktion-Schalter/dp/B00DG0KQBE/ref=sr_1_1?ie=UTF8&qid=1500925768&sr=8-1&keywords=usb+taster
or by some 'hand button' even with bluetooth.
How can this be implemented?

**Comment by Tomtaste** [comment]
My favourite is this one:
https://www.amazon.de/FU%C3%9F-GROBHANDTASTER-1S1%C3%96-FAK-R-KC11/dp/B0014DQI5S/ref=sr_1_1?ie=UTF8&qid=1502548311&sr=8-1&keywords=grobhandtaster
Any ideas how to implement?

**Comment by wirthual** [comment]
Hi,

I think this is really helpful: https://github.com/PiPHP/GPIO

**Comment by andi34** [comment]
Via GPIO possible now.
Via USB should be possible too if accesskey is definedhttps://github.com/andreknieriem/photobooth/blob/dc99f6dcf8465d994d8d5152bcf38edba8efa746/index.php#L68
