### ISSUE TITLE
Success !! finished project  (nearly)

### ISSUE THREAD

**Issue by vdubuk** [andreknieriem/photobooth#103]
Hi to all,
First off all thank you to everyone who has contributed to this project. I just wanted to share with everyone my finished project for a Wedding Postbox / Photo kiosk

RPI 3
RaspiCam
10" touch monitor

![IMG_20191006_162540](https://user-images.githubusercontent.com/4080228/66271640-4f7f0000-e858-11e9-894e-2272e29e17fa.jpg)

![IMG_20191006_162327](https://user-images.githubusercontent.com/4080228/66271644-56a60e00-e858-11e9-9c10-6d15de454904.jpg)

Rather messy inside 
![IMG_20191006_162708](https://user-images.githubusercontent.com/4080228/66271663-9cfb6d00-e858-11e9-8ef7-03dd3840141d.jpg)

And a final print
![IMG_20191006_163051](https://user-images.githubusercontent.com/4080228/66271667-b00e3d00-e858-11e9-9934-7ce8df46c421.jpg)

**Comment by sualko** [comment]
Looks awesome :tada: :+1: Thanks for sharing. Hope you have a good time with your photobooth.

**Comment by andi34** [comment]
By @thymon13 :

> Hello,
> 
> I 'm glad to present you my Photobooth.
> Thanks to all the people who contribute to the improvement of this project !
> 
> I was inspired by other photobooth on the internet. And I liked the one that looks like Instagram.
> **So I started !!**
> 
> ![7](https://user-images.githubusercontent.com/18228022/64514333-b6a5a500-d2ea-11e9-8093-7c29f6289915.jpg)
> ![8](https://user-images.githubusercontent.com/18228022/64514336-b6a5a500-d2ea-11e9-82ef-53653a281b0a.jpg)
> 
> **Here it is in action**
> 
> ![2](https://user-images.githubusercontent.com/18228022/64514412-d89f2780-d2ea-11e9-8771-bcc8e54531f3.jpg)
> ![3](https://user-images.githubusercontent.com/18228022/64514413-d89f2780-d2ea-11e9-96bf-732dd2f82d05.jpg)
> ![1](https://user-images.githubusercontent.com/18228022/64514414-d89f2780-d2ea-11e9-915c-273268e4798e.jpg)
> 
> **Video test QR Code :**
> 
> https://youtu.be/EG5JD2_vvRg
> 
> **I recently added the print function. And I have edit the file "print.php" to add my own frame around the picture (before the last update on this project)**
> 
> ![6](https://user-images.githubusercontent.com/18228022/64514571-2c117580-d2eb-11e9-9cfd-296eb3aa05d1.jpg)
> ![9](https://user-images.githubusercontent.com/18228022/64514572-2c117580-d2eb-11e9-8c07-3a40b1f2fa1a.jpg)
> 
> **The heart of my baby :) :)**
> 
> ![10](https://user-images.githubusercontent.com/18228022/64514596-3a5f9180-d2eb-11e9-97d9-9b5cdd698a18.jpg)


By @flighter18 

> @thymon13 that looks really amazing!
> great work!
> mine is not that professional but I really like my bluetooth buzzer :)
> ![IMG_8798](https://user-images.githubusercontent.com/26125704/64518775-bd341c80-d2ea-11e9-9ce6-093c3ace43af.jpg)
> ![IMG_8896](https://user-images.githubusercontent.com/26125704/64518780-c02f0d00-d2ea-11e9-9abd-4c56cd7c047b.jpg)
> 
> @andi34 let's start a wiki. that would be great


By @Nie-Oh 

> Hello,
> 
> Here are some Pictures of my Photobooth.
> 
> ![IMG_20190413_190746_resized_20190910_072539813](https://user-images.githubusercontent.com/48091156/64586798-b3b7bc80-d39d-11e9-9679-047fd21077f9.jpg)
> 
> The Case is made of IKEA 1x1 Kallax. I use a Touchscreen Monitor directly connected to the Raspi.
> 
> ![IMG_20190413_190728_resized_20190910_072540057](https://user-images.githubusercontent.com/48091156/64586430-8ae2f780-d39c-11e9-9160-e2c22a1302fd.jpg)
> 
> Also, but i have no Images of these Setup, i have an 24" Medion All in One PC and a Mitsubishi 9550 Photoprinter. Every Minute i syncronize the Pictures with WINscp. The Customers can use these PC for printing the Pictures.....

**Comment by andreknieriem** [comment]
So many cool Projects :) love them and thanks to all for your support on my initial project!
