### ISSUE TITLE
v2.0.0: make blur count optional

### ISSUE THREAD

**Issue by andi34** [andreknieriem/photobooth#111]
Depending on the hardware and photo resolution the blur effect takes to long and aborts.

Prepared: https://github.com/andreknieriem/photobooth/pull/90/commits/b96bda67d878a40ad400dc5461a1fa7ca126296f

**Comment by andi34** [comment]
@msmedien you could try changing `$blur = 5;` to a lower value . But blur will be softer.

**Comment by sualko** [comment]
If you get a timeout, just increase the timeout.

**Comment by andi34** [comment]
It shouldn't take ages, else it's not userfriendly.
