### ISSUE TITLE
v2.0.0: add wiki to dependencies

### ISSUE THREAD

**Issue by andi34** [andreknieriem/photobooth#112]
You don't have internet access everywhere. Having a local documentation (especially FAQ) would be a good thing in some cases,

**Comment by sualko** [comment]
I don't think that a wiki should be part of the dependencies, but you could add it to the wiki how you could get a copy of it. Just clone https://github.com/andreknieriem/photobooth.wiki.git

**Comment by andi34** [comment]
https://github.com/andreknieriem/photobooth/wiki#clone-this-wiki
