### ISSUE TITLE
v2.0.0: Gallery Buttons (Print/QRCode) doesn't work on IOS 12

### ISSUE THREAD

**Issue by flighter18** [andreknieriem/photobooth#116]
If I open a pic in the gallery, the button in the right corner doesn't work except the close button. I uploaded a video:
https://youtu.be/e3e1k_bvFxc

**Comment by flighter18** [comment]
@sualko i checked out your fix:
```
commit b889e2da19ea30580c9e55f685fe8e7a98166b56 (HEAD)
Merge: 5cee070 331d1ef
Author: raphael.schib <raphael.schib@kara-network.ch>
Date:   Fri Oct 11 17:15:34 2019 +0100

    Merge commit '331d1ef4adeb4269893bb7bdc840fd0b2b1c6ec4' of https://github.com/andreknieriem/photobooth into HEAD

commit 331d1ef4adeb4269893bb7bdc840fd0b2b1c6ec4
Author: sualko <klaus@jsxc.org>
Date:   Fri Oct 11 15:15:14 2019 +0200

    fix gallery buttons on small screens

    fix #116
```
but unfortunately it still not working

**Comment by andi34** [comment]
@flighter18  you need to run `yarn build` again.

Once something is in master branch merged it's enough to `git fetch origin && git checkout origin/master && yarn build` (you must have cloned from here)

**Comment by flighter18** [comment]
@andi34 
I have done the following 

```
sudo -u www-data -s
git remote add andreknieriem https://github.com/andreknieriem/photobooth
git fetch andreknieriem
git checkout andreknieriem/master
yarn build
exit
```

but the buttons dosen't work.

**Comment by andi34** [comment]
If no error was visible and it was telling `git checkout` was fine it should be ok. It'll tell you in terminal if it can not checkout because of uncommitted changes for example (in case you made some changes by hand in your source)

**Comment by flighter18** [comment]
@andi34 no error was visible. so I think the button does still not work.

**Comment by andi34** [comment]
You can check `git log` if latest commit hash matches the one here, should be `331d1ef4adeb4269893bb7bdc840fd0b2b1c6ec4` if you're not sure

**Comment by flighter18** [comment]
@andi34 thank you for this hint.

```
[root@raspberrypi:/var/www/html# git log
commit 331d1ef4adeb4269893bb7bdc840fd0b2b1c6ec4 (HEAD, andreknieriem/master)
Author: sualko <klaus@jsxc.org>
Date:   Fri Oct 11 15:15:14 2019 +0200]
```
So it matches.

**Comment by andi34** [comment]
You're able to test on Android?
Only specific browser?

**Comment by flighter18** [comment]
i do not have any android device but i tested it with 3 browser on ipad and iphone.
none of them works.

**Comment by andi34** [comment]
Ok. Might be able to check in the morning on Android. Will have to setup my pi again as access point for it.

**Comment by andi34** [comment]
![Screenshot_20191011-210833](https://user-images.githubusercontent.com/6080900/66678160-8a73a000-ec6b-11e9-84cd-fbae8df711e1.jpg)
![Screenshot_20191011-210823](https://user-images.githubusercontent.com/6080900/66678173-92cbdb00-ec6b-11e9-8aa0-a6d624af64e2.jpg)
![Screenshot_20191011-210818](https://user-images.githubusercontent.com/6080900/66678177-95c6cb80-ec6b-11e9-8b21-0372f3c0ca3e.jpg)
![Screenshot_20191011-210804](https://user-images.githubusercontent.com/6080900/66678188-9a8b7f80-ec6b-11e9-872a-0cc1465d317d.jpg)
![Screenshot_20191011-210750](https://user-images.githubusercontent.com/6080900/66678193-9d867000-ec6b-11e9-8c21-8516bd7ba539.jpg)
![Screenshot_20191011-210655](https://user-images.githubusercontent.com/6080900/66678201-a119f700-ec6b-11e9-834a-c80db988f526.jpg)
![Screenshot_20191011-210649](https://user-images.githubusercontent.com/6080900/66678211-a4ad7e00-ec6b-11e9-9813-7858ba9dd577.jpg)






Quickly tested 😂 no issues on my phone , Android 9, Chrome browser, OnePlus 6.

![Screenshot_20191011-210852](https://user-images.githubusercontent.com/6080900/66678156-88114600-ec6b-11e9-976b-2670afee0f5f.jpg)

**Comment by flighter18** [comment]
I tested it now also on IOS 13. here it works too 🙈. So the problem is IOS 12

**Comment by flighter18** [comment]
🥴 my ipad is to old for IOS13 😅 shit

**Comment by andi34** [comment]
https://forum.webflow.com/t/button-not-responding-in-safari-on-iphone/51418
Seems a known issue?
