### ISSUE TITLE
Neue Sprache (Griechisch)

### ISSUE THREAD

**Issue by fossil74** [andreknieriem/photobooth#122]
Hallo Leute,
weiß nicht ob es hier an der Richtigen stelle gepostet ist. Darum löschen wenn Falsch.

Hier eine neue Sprache für das Photobooth.
Mein Griechisch ist nicht Perfekt daher mit einem Online Übersetzer gemacht. Bitte ändern wenn was falsch ist.

[Griechisch](https://github.com/fossil74/Photobooth/blob/master/resources/lang/gr.js)

**Comment by andreknieriem** [comment]
Mega! Vielen Dank!

**Comment by andi34** [comment]
@fossil74 vielen Dank! Ich habe entsprechend eine passende Pullrequest erstellt.

> Mein Griechisch ist nicht Perfekt daher mit einem Online Übersetzer gemacht. Bitte ändern wenn was falsch ist.
> 

Ist dein griechisch so gut, das du bestätigen kannst das alles richtig ist? Ein gewisser Qualitätsstandard sollte natürlich gegeben sein wenn neue sprachen hinzukommen.

**Comment by fossil74** [comment]
@andi34 
bin selbst Grieche aber in Deutschland geboren. Also ich kann bestätigen das es zu 90% richtig ist. 
Manches kann man nicht so Übersetzen wie es da steht, Galerie zb. gibts in GR nicht in dieser Form wie in DE oder in US. 

Aber ich lass gerne nochmal einen zweiten drüber schauen wenn Ihr wollt, ist kein problem das zu machen.

**Comment by andi34** [comment]
@fossil74 alles gut, wollte nur nochmal nachhaken

**Comment by andi34** [comment]
Achso, muss auch nicht 1:1 sein, glaube statt Gallery wäre `Συλλογή` passend, oder?

**Comment by flighter18** [comment]
ich würde sonst noch eine Griechen kennen, die in Griechenland lebt.
Villeicht könnte sie nochmals darüber schauen?

**Comment by andi34** [comment]
Vllt kann man in Zukunft auf crowdin zurückgreifen für Übersetzungen. Im Zweifelsfall müsste man schauen ob das format angepasst werden kann.

https://crowdin.com/page/open-source-project-setup-request

Habe crowdin für 2 große Android Projekte gemanaged in der Vergangenheit, müsste mich dann nur wieder reinfuchsen.

Generell gilt: man kann nicht alles 1:1 übersetzen und muss man auch nicht. So wie es im entsprechenden Land im alltäglichen Sprachgebrauch benutzt wird.
Soweit ich weiß würde man es aus dem griechischen ins deutsche übersetzen würde man "Sammlung" anstelle von "Gallery" nehmen.

**Comment by fossil74** [comment]
> Achso, muss auch nicht 1:1 sein, glaube statt Gallery wäre `Συλλογή` passend, oder?

Wenn dann so Φωτογραφική συλλογή

**Comment by sualko** [comment]
@fossil74 thanks for your contribution :tada:. If you have further chances, just open the [gr.js](https://github.com/andreknieriem/photobooth/blob/master/resources/lang/gr.js) file and click on the pencil to create a new pull request. 

![2019-10-14 21 01 44 github com bdf238182075](https://user-images.githubusercontent.com/2974196/66776103-ec2f4680-eec5-11e9-948e-10c165e85b8d.png)
