### ISSUE TITLE
Kleine Vorschau bei den Verschiedenen Bildflter

### ISSUE THREAD

**Issue by fossil74** [andreknieriem/photobooth#127]
Hallo liebe Entwickler,
wäre es möglich ein kleines live bild zu generieren sobald man auf Bildfilter drauf geht??
Sodas die sehen wie das Foto aussehen könnte wenn die diesen Filter nutzen.

Sollte es möglich sein wäre cool aber es Eilt nicht.

**Comment by andi34** [comment]
Duplicate, https://github.com/andreknieriem/photobooth/issues/96
