### ISSUE TITLE
Feature Request - Optionpage

### ISSUE THREAD

**Issue by HerrVonundZu** [andreknieriem/photobooth#13]
Hey there
it would be really helpfull to have an admin/optionspage where you can deactivate/activate the qrcode/printbutton, reset fotos/data/thumbnails etc...

**Comment by andreknieriem** [comment]
Yes, thats true. Will try to add it soon.

**Comment by soko1988** [comment]
Hey @andreknieriem,
great Project!
Possible to Secure the Adminpage with a PIN-Code or RFID-Chip?
Also for Issue #9 : Configure/Upload the Overlays (Text / Image) and maybe set the place for that overlay.

**Comment by Tiptronic1812** [comment]
Hey there, is the admin/optionpage already implemented? Where can I find it?

**Comment by andreknieriem** [comment]
Hi, small update. Was working on it. Think it will be ready soon.

http://photobooth.andrerinas.de/admin/

**Comment by ChrisKram** [comment]
Looks great!

**Comment by andreknieriem** [comment]
Now availabled
