### ISSUE TITLE
Problem mit Hochzeitssymbol

### ISSUE THREAD

**Issue by obkram** [andreknieriem/photobooth#130]
Ich habe seit gestern ein Problem welches ich heute bei einem frisch aufgesetzten System immer noch nachvollziehen kann.
Ich kann das Symbol für Hochzeiten nur auswählen und dauerhaft speichern wenn keine Namen eingetragen sind. Sobald ich einen Namen eintrage und speichere steht dort wieder Symbol wählen. Einzige Änderung zum Standart ist das Livewallpaper. Kann das jemand bestätigen

**Comment by andi34** [comment]
Please use the template and fill it instead removing everything:
```
**Describe the bug**
<!-- A clear and concise description of what the bug is. -->

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Photobooth**
- Did it work before? [yes/no]
- Which version of Photobooth are you using?

**Additional context**
<!-- Add any other context about the problem here. -->
```

**Comment by andi34** [comment]
How does your `config/my.config.inc.php` look like? Please remove mail parts if added to not share them public.

**Comment by andi34** [comment]
issue seems to be mentioned below the URL

![Screenshot_2019-10-16_20-04-08](https://user-images.githubusercontent.com/6080900/66945932-2fb5bc00-f050-11e9-9224-76d3780cf173.png)

**Comment by obkram** [comment]
Also meine my.config.inc.php sieht wie folgt:
<?php
$config = array (
  'is_wedding' => true,
  'wedding' => 
  array (
    'groom' => 'S',
    'bride' => 'A',
  ),
);

**Comment by obkram** [comment]
Sorry, der Rest wurde irgendwie geschluckt. hoffe es klappt jetzt.
# <?php
# $config = array (
# 'is_wedding' => true,
# 'wedding' => 
#  array (
#   'groom' => 'S',
#    'bride' => 'A',
#  ),
#);

**Comment by andi34** [comment]
@obkram https://github.com/andreknieriem/photobooth/commit/74c6c2cb116240abd0fe120c87483ba1d06c6470 is not a proper fix.

This could happen on other options too, but it should work for now here.
We need to save the whole array if one part of an array is changed, atm it excludes the default config from the array,

Here it must look like this:
```
  'wedding' => 
  array (
    'groom' => 'Name 2',
    'bride' => 'Name 1',
    'symbol' => 'fa-heart-o',
  ),
```
