### ISSUE TITLE
Brauche kleinen Anstoß

### ISSUE THREAD

**Issue by mdkhome** [andreknieriem/photobooth#136]
Hi, ich kenne mich nicht gut in der Sache aus, aber ich versuche mein bestes 💃 
Ich glaube ich habe irgendwo einen Gedankenfehler, komme aber nicht drauf. Währe super wenn einer mir helfen könnte.

Denke das ich nach der Anleitung gegangen bin, aber egal wie oft ich mein Rasperry neu aufsetze, komme ich nicht weiter.

Immer wenn ich den Respi über browser aufrufe, bekomme ich keine richtige Grafikseite angezeigt sondern nur links. Und unter /Admin kann ich nix ändern da ich kein speichern Button oder so was finde.
 Ich bedenke mich schon mal für die Hilfe.
![web](https://user-images.githubusercontent.com/18899511/67004323-54f20b00-f0e0-11e9-8cab-88fd1bb02dba.jpg)

**Comment by sualko** [comment]
Please use the issue template and provide the log of all steps you performed.

**Comment by mdkhome** [comment]
Also ich weiß nicht weiter, ich habe mich an die Anleitung gehalten. Immer und immer wieder. Aber immer das selbe Ergebnis, Keine Idee woran es liegen könnte? Nutze Respberry pi 3b+ mit Strech Desktop. Habe alle Updates und Upgrades durchgeführt....

**Comment by sualko** [comment]
> Immer und immer wieder

I believe you, but I have no crystal ball or superpowers (I have, but I'm not allowed to talk about it :wink:). Without logs we can't debug this.

> Keine Idee woran es liegen könnte?

You didn't create the css files, but without logs I can't tell you why this failed.

**Comment by andi34** [comment]
> Also ich weiß nicht weiter, ich habe mich an die Anleitung gehalten. Immer und immer wieder. Aber immer das selbe Ergebnis, Keine Idee woran es liegen könnte? Nutze Respberry pi 3b+ mit Strech Desktop. Habe alle Updates und Upgrades durchgeführt....

Yarn installed?
Any errors while running `yarn install` or `yarn build`?

**Comment by mdkhome** [comment]
OK, dachte du würdest deine Glaskugel nicht nur für Reichtum und Frauen nutzen ;)
Welches Log brauchst du/ihr denn? Bin nicht sehr bewandert in sachen Linux.
Muss ich noch was erstellen, dachte hier wäre alles startbereit.?!

**Comment by andi34** [comment]
> OK, dachte du würdest deine Glaskugel nicht nur für Reichtum und Frauen nutzen ;)
> Welches Log brauchst du/ihr denn? Bin nicht sehr bewandert in sachen Linux.
> Muss ich noch was erstellen, dachte hier wäre alles startbereit.?!

https://github.com/andreknieriem/photobooth/wiki/Installation-on-Debian

**Comment by mdkhome** [comment]
OK danke dafür schonmal, ich versuche es mit dem Tutorial mal

**Comment by andi34** [comment]
> OK danke dafür schonmal, ich versuche es mit dem Tutorial mal

It's mentioned in the README to follow the instructions. Also updating from 1.9 or older should be done by a clean new setup as there have been big changes in all parts of the source, also security improvements (no need for sudo rights anymore to take pictures).

**Comment by mdkhome** [comment]
Stretch hatte ich nur Installiert da die meisten Tutorials die ich so gefunden hatte auf Stretch aufbauen. Aber mit dem Link von Andi34 versuch ich nun erneut mein Glück. Schon mal danke an alle die mir Rückmeldung gegeben hatten.

@obkram: Die IP Adresse ist mein lokales Netzwerk, worüber auch der PI angeschlossen ist

**Comment by andi34** [comment]
@mdkhome am besten immer die hier in der Repo angegeben Instruktionen folgen, wir halten das hier immer aktuell damit es zum Source passt.

**Comment by mdkhome** [comment]
Soeben hab ich es aufgespielt, läuft alles wie am Schnürchen, vielen Dank.
