### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by markussiegert** [andreknieriem/photobooth#139]
Hallo in die Runde,
erstmal vielen Dank an die Entwicklergruppe für die Super Arbeit.

mir Sind in der Version 2 zwei bis drei sachen aufgefallen:
1. ich kann die Weboberfläche in Googles Chrome nicht darstellen, ist für mich aber nicht so das Problem ;)
2. mir ist aufgefallen das, wenn man die Bilder über die Adminseite löscht, die links in der Galerie erhalten bleiben.
3. da ich gern das Hintergrundbild bei Bedarf ändere, lässt sich das aufgrund fehlender Rechte als User pi nicht mehr realisieren.
Ich weis nicht ob es sich hierbei um Fehler handelt oder ich einfach keine Ahnung habe wie es einfach geht.

**Comment by sualko** [comment]
> ich kann die Weboberfläche in Googles Chrome nicht darstellen, ist für mich aber nicht so das Problem

Please open a new issue for this and provide a proper javascript log from your browser (use ctrl+I the debug console).

> mir ist aufgefallen das, wenn man die Bilder über die Adminseite löscht, die links in der Galerie erhalten bleiben.

I can confirm this issue and will provide a fix asap.

> da ich gern das Hintergrundbild bei Bedarf ändere, lässt sich das aufgrund fehlender Rechte als User pi nicht mehr realisieren.

An easy fix would be the following, assuming you installed photobooth inside `/var/www/html`.

```
sudo chgrp -R pi /var/www/html/resources/
sudo chmod -R g+w /var/www/html/resources/
```

**Comment by markussiegert** [comment]
Thanks a lot for your work and help.

**Comment by obkram** [comment]
#mir ist aufgefallen das, wenn man die Bilder über die Adminseite löscht, die links in der Galerie erhalten bleiben.

Das kann ich bestätigen. Ist mir auch aufgefallen.

# da ich gern das Hintergrundbild bei Bedarf ändere, lässt sich das aufgrund fehlender Rechte als User pi nicht mehr realisieren.
Ich weis nicht ob es sich hierbei um Fehler handelt oder ich einfach keine Ahnung habe wie es einfach geht.

Wenn du den PhotoBooth auf einem RPI laufen hast dann öffne die Console und gib...
sudo pcmanfm
... ein. Dann wird der Filemanager mit Adminrechten geöffnet und du kannst die Files ändern und bearbeiten
