### ISSUE TITLE
Feature Request - Live/Preview

### ISSUE THREAD

**Issue by HerrVonundZu** [andreknieriem/photobooth#14]
it would be nice to have a preview 
in the comments on your website a guy wrote something about inserting a motion stream as backgroundpicture. Maybe it is possible to show this webcam/raspberrypicamstream in a tiny frame on the startscreen and as huge backgroundvideo when the countdown starts.

**Comment by TKnpl** [comment]
Would be a great enhancement! I would also be very interested in this extension.
If possible, a new part in the configuration file will be nice, to disable/enable the live-view while the countdown is running.
Also streaming the live-view from the dslr-camera via. gphoto2 or ffmpeg would be great. But I think this requires a serverside service... hopefully raspberrypi is powerfull enough.

**Comment by andreknieriem** [comment]
Is now via device webcam availabled. Just activate in /admin

**Comment by ChrisKram** [comment]
Is that only an Option if I use a tablet with a camera or will it also work with a Raspberry Pi camera?

**Comment by UncleCCC** [comment]
Läuft das nur mit der Tablet Kamera?
Oder kann ich zB eine Webcam für LiveView verwenden?

**Comment by UncleCCC** [comment]
Ah, sry, bin in sachen Programmierung nicht soo Fit..
Aber sehe ich es richtig das MotionEye für den Stream sorgt?

**Comment by andi34** [comment]
@nie-oh might be able to give proper information about he setup on his pi with USB webcam
