### ISSUE TITLE
Keine Darstellung in Google Chrome

### ISSUE THREAD

**Issue by markussiegert** [andreknieriem/photobooth#141]
ich kann die Weboberfläche nicht im Chrome anzeigen lassen.
in Edge und Firefox geht es.
Wurde gebeten ein log mitzugeben.

Photbooth Version 2

[log.txt](https://github.com/andreknieriem/photobooth/files/3744021/log.txt)

![Unbenannt](https://user-images.githubusercontent.com/56723586/67096742-0fedd780-f1b9-11e9-9415-7649734bad3f.jpg)

**Comment by sualko** [comment]
Did you make any modifications? Because it seams that you load some javascript files twice.

Can you go to the network tab, inside the developer console, right click on any item, choose "Save all as HAR with content" and upload the file here, or send it to klaus@jsxc.org?

**Comment by markussiegert** [comment]
First of all thanks for the quick help.
No, I think I installed everything according to the instructions and in
other browsers it works.
The desired file is in the appendix.
I wish you a nice evening and a nice weekend.
Yours sincerely
Markus Siegert

Am Fr., 18. Okt. 2019 um 15:21 Uhr schrieb Klaus <notifications@github.com>:

**Comment by sualko** [comment]
@markussiegert if you reply to the github notification the attachment gets removed. Please send it directly to klaus@jsxc.org, or upload it directly to this issue.

**Comment by markussiegert** [comment]
if send it.

**Comment by andi34** [comment]
Tested on Chrome 2 days ago:
> **Screenshots**
> ![Screenshot_2019-10-16_20-21-02](https://user-images.githubusercontent.com/6080900/66947113-94721600-f052-11e9-8e7c-90b07e2900e9.png)
> 
> **Environment (please complete the following information):**
> 
> * OS: Xubuntu
> * Browser : Chrome
> * Version:  77.0.3865.90 (Official Build) (64-bit)

**Comment by sualko** [comment]
The log looks good. Which version of chrome do you use? Can you try to [start chrome without extensions](https://www.techsupportall.com/start-google-chrome-without-extensions/)?

**Comment by markussiegert** [comment]
I tried it in incognito mode and it works. Thanks for your help.
