### ISSUE TITLE
No saving after chroma keying

### ISSUE THREAD

**Issue by obkram** [andreknieriem/photobooth#144]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

**Photobooth**
- Did it work before? [yes/no]
- Which version of Photobooth are you using?

**Additional context**

**Comment by obkram** [comment]
Sorry, I pressed the enterkey to early .
Take a picture
Go to gallery
Select the picture
Select chroma keying
Select a Background and press save

Error: there will always shown save an nothing more will happen.

Aktuelles Raspbian
Aktueller Standart-Browser von Raspbian

**Comment by sualko** [comment]
Thanks for your report. There was an include missing.

**Comment by sualko** [comment]
Btw, do you know why the preview is that small? It could be way bigger.

**Comment by obkram** [comment]
@sualko you are very quickly. I tested it on my system. The changes will work fine. Thank you.
