### ISSUE TITLE
Enhance chroma keying

### ISSUE THREAD

**Issue by sualko** [andreknieriem/photobooth#146]
I did some tests with an example image which I found in the internet and I think the result is very disappointing. A quick test with [seriously.js](https://github.com/brianchirls/Seriously.js/) looked much better. The library was not updated in the last years, but the current library is also not that active :wink:. I think we could switch libraries, if we look at #126. One think we should test before, if seriously.js is also running on a raspberry, because I think it is using webgl.

Original image:
![2019-10-18 21 11 09  796798eee342](https://user-images.githubusercontent.com/2974196/67123414-89ed8300-f1f0-11e9-99bd-b82cd56adf49.png)

Current implementation:
![2019-10-18 21 10 48 localhost ca927eeb8e22](https://user-images.githubusercontent.com/2974196/67123428-92de5480-f1f0-11e9-867a-c508452fc9d9.png)

Seriously.js:
![2019-10-18 21 10 35  4baa330ca932](https://user-images.githubusercontent.com/2974196/67123445-9e318000-f1f0-11e9-9df2-55248d6bd5dd.png)

```
<!DOCTYPE html>
<html>
<head><title>Seriously.js Tutorial</title></head>
<body>
        <img src="chroma.png" id="test" />
        
        <canvas id="canvas" width="1600" height="900" style="background-color: yellow"></canvas>

	<script src="seriously.js"></script>
	<script src="effects/seriously.chroma.js"></script>
	
	<script>        
        (function() {
		let seriously = new Seriously();
		let image = seriously.source('#test');
		let target = seriously.target('#canvas');
		let chroma = seriously.effect('chroma');

		chroma.source = image;
		target.source = chroma;
		seriously.go();
	}());
	</script>
</body>
</html>
```

**Comment by andi34** [comment]
Wow, that's a big difference.

**Comment by andi34** [comment]
Available since Photobooth v3
https://photoboothproject.github.io/Changelog
