### ISSUE TITLE
Two suggestions for Chromakeying

### ISSUE THREAD

**Issue by obkram** [andreknieriem/photobooth#150]
Leider ist bei Englisch zu bescheiden um es zu beschreiben:

1. Nach der Aufnahme eines Bildes wird man auf die Seite des gerade aufgenommenen Bildes weitergeleitet. Von dort aus muss man erst in die Galerie wechseln um Chromakeying ausführen zu können. Mein Vorschlag wäre den Gallerybutton unten in der Viererdarstellung durch die Weiterleitung ( Pinsel ) nach Chromakeying zu ersetzen.

2. Befindet man sich in der Gallery und man hat zuvor ein Bild mit Chromakeying gespeichert dann ist es möglich dieses erneut in der Gallery auszuwählen. Ist dieses bereits bearbeitete Bild dann geöffnet und man versucht erneut Chromakeying anzuwählen dann erscheint eine Fehlermeldung. Vielleicht könnte man die erneute Nachbearbeitung eines mit Chromakeying bearbeiteten Bildes in der Gallery unterdrücken, es in der Gallery als bearbeitet kennzeichnen ( Rahmenfarbe ) oder zumindest den Text der Fehlermeldung ändern in .. 
Eine nochmalige Bearbeitung ist leider nicht möglich

Danke ihr Lieben

**Comment by andi34** [comment]
Duplicate https://github.com/andreknieriem/photobooth/issues/126

**Comment by obkram** [comment]
Punkt 1. sehe ich ein. Da hast du recht, das gibt es wohl schon
wie sieht es denn mit Punkt 2. aus? Unterbindung einer erneuten Bearbeitung mit Chromakeying von bereits mit Chromakeying bearbeiteten Bildern?
![IMG_3161](https://user-images.githubusercontent.com/33160929/67142752-91e70a80-f264-11e9-914b-3d4d715adb3d.jpeg)

**Comment by andi34** [comment]
Füg das gerne da noch mit ein. Geht ja darum, dass der komplette Workflow überarbeitet werden soll.

**Comment by andi34** [comment]
Bezüglich des Workflow überarbeiten:
Direkt nach Erstellung des Bildes wird der Hintergrund gewählt.

 Inwieweit von der Gallerie aus dann noch die Möglichkeit für keying gegeben sein soll / muss , muss noch entscheiden werden.

**Comment by obkram** [comment]
ok, danke
