### ISSUE TITLE
Show date below images in gallery not working

### ISSUE THREAD

**Issue by andi34** [andreknieriem/photobooth#151]
**Describe the bug**
White index after enableing the option to show date below images in gallery

**To Reproduce**
1. Enable dateformat images
2. enable option to show date below images in gallery
3. save your changes
4. open index
5. only white page

**Expected behavior**
Show index, show date below images in gallery

**Error from console**
```
Fatal error: Uncaught Error: Call to a member function format() on bool in /var/www/html/template/gallery.template.php:16 Stack trace: #0 /var/www/html/index.php(175): include() #1 {main} thrown in /var/www/html/template/gallery.template.php on line 16
```
**Environment (please complete the following information):**
 - OS: Raspbian buster
 - Browser: Chromium Version 74.0.3729.157 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit)

**Photobooth**
- Did it work before? 
yes

- Which version of Photobooth are you using? 
latest stable

**Comment by sualko** [comment]
For me it's not working for freshly taken pictures, but if you reload the page the date is shown (even if it's ugly). Can you confirm this behavior?

![2019-10-21 14 07 15 localhost 1908465ded11](https://user-images.githubusercontent.com/2974196/67203775-48d1ba80-f40c-11e9-9fd3-9d64d9b21a10.png)

**Comment by sualko** [comment]
I added a fix for the ugly date and a check if the filename is in date format. So it looks now like this:

![2019-10-21 14 26 13 localhost 317b7a7599f6](https://user-images.githubusercontent.com/2974196/67205944-0fe81480-f411-11e9-9cf7-927b766b5649.png)

**Comment by andi34** [comment]
Great! Thanks a lot!
