### ISSUE TITLE
Bug fix release (2.0.2)

### ISSUE THREAD

**Issue by sualko** [andreknieriem/photobooth#152]
I would like to create another bug fix release, so that we can start working on 2.1.0. Is there anything left to do?

Changed commits since last release: https://github.com/andreknieriem/photobooth/compare/v2.0.1...master

**Comment by andi34** [comment]
Only the installation script, everything else is mentioned for 2.1.0

**Comment by sualko** [comment]
Great. Than I will release another version in a minute. Btw I have created a [release checklist](https://github.com/andreknieriem/photobooth/wiki/Release-checklist). If you have anything to add or discussion, please write me an email.
