### ISSUE TITLE
Photo Collage Frame

### ISSUE THREAD

**Issue by Real2222** [andreknieriem/photobooth#157]
**Is your feature request related to a problem? Please describe.**
Resize the Photos and merge with a custom position to a Collage Frame

**Describe the solution you'd like**
Where can i customize and resize the images in the Collage ?

**Describe alternatives you've considered**
Customizable Collage Frame in the Admin Backend

**Additional context**
Like this Preview:
<a href="https://ibb.co/Q8mHkP6"><img src="https://i.ibb.co/DGKMY97/photobooth.jpg" alt="photobooth" border="0"></a>

**Comment by andi34** [comment]
Collage creation is done here:
https://github.com/andreknieriem/photobooth/blob/master/lib/collage.php

Print frame is done here:
https://github.com/andreknieriem/photobooth/blob/master/api/print.php#L54
or
https://github.com/andreknieriem/photobooth/blob/master/api/print.php#L88
(Depending on QR print)

**Comment by sualko** [comment]
> Where can i customize and resize the images in the Collage ?

That's currently not possible and also currently not on our roadmap.

**Comment by andi34** [comment]
Part of Photobooth V4
https://github.com/PhotoboothProject/photobooth/pull/26
