### ISSUE TITLE
FAQ - Frequently asked questions | How to hide the Mouse Cursor? Option 2

### ISSUE THREAD

**Issue by flighter18** [andreknieriem/photobooth#168]
If we hide the cursor with unclutter, the mouse cursor appears for a short time, while tipping on the touchscreen. 

To hide the cursor 100%  edit the /etc/lightdm/lightdm.conf by:
uncomment **xserver-command=X** 
and add **-nocursor** at the end of the line

`xserver-command=X -nocursor` 

restart rasperrypi. Now you get a tablet feeling :)
Maybe we could at this idea to the wiki?

**Comment by andi34** [comment]
Instead unclutter?

**Comment by flighter18** [comment]
> Instead unclutter?

hm why not?

**Comment by andi34** [comment]
> > Instead unclutter?
> 
> hm why not?

Wanted to make sure

**Comment by sualko** [comment]
I added it to the faq page. Thanks for sharing.
