### ISSUE TITLE
Fehlerhafte Positionierung des QR Codes aus der Vorschau heraus

### ISSUE THREAD

**Issue by TKnpl** [andreknieriem/photobooth#17]
Hallo,
vielen Dank, dass du dieses tolle Projekt zur Verfügung stellst.
Mir ist ein Bug aufgefallen:
Wenn man ein Foto macht und anschließend direkt den QR Code generiert, ist die Darstellung des QR Codes fehlerhaft, sodass man ihn nicht abscannen kann (siehe Bild).
Ich denke hier ist etwas in der class="qr" nicht richtig. Vielleicht annst du dir das ja einmal ansehen.
Vielen Dank!
![qr-failure-photobooth](https://user-images.githubusercontent.com/33960711/33214841-d70c997c-d12d-11e7-9f3d-c8a9c0c43ce4.png)

**Comment by andreknieriem** [comment]
* Behoben
