### ISSUE TITLE
Button Border Radius

### ISSUE THREAD

**Issue by obkram** [andreknieriem/photobooth#188]
![Border Button](https://user-images.githubusercontent.com/33160929/68364778-3c996d00-012f-11ea-8f81-1244a346611c.jpeg)
**Is your feature request related to a problem? Please describe.**
Ich habe bei mir heute eine Einstellung ausprobiert um die Button etwas weicher erscheinen zu lassen. Es betrifft alle Button Ausnahme des Button X. Soweit habe ich keine Probleme dadurch feststellen können.

**Describe the solution you'd like**
Nach Änderung der Style.css erscheinen die Button etwas weicher und nicht ganz so kantig. 

**Describe alternatives you've considered**
Zur Umsetzung habe ich in der Style.css unter die Zeile 108 und in der admin.css unter der Zeile 131 noch folgenden Parameter angefügt:
....
border-radius: 10px; }

**Additional context**
Vielleicht gefällt euch das ja auch.

**_Edit by Andi34_**
Commits for smooth edges:
- https://github.com/andi34/photobooth/commit/0cb1141a5d39d197c4bf7d50cd6aeed93571943c
- https://github.com/andi34/photobooth/commit/2979af0ea64818127eadbb1bdbb31d6283886985
- https://github.com/andi34/photobooth/commit/15bdc244eff3621b35a249ade301ce0efa5d0872
- https://github.com/andi34/photobooth/commit/94f6e2f0f638d5723dfeca48c4910565ae8595e3
- https://github.com/andi34/photobooth/commit/3c1ef3ae510ba04658817ae2c604e23f8c2d338c
- https://github.com/andi34/photobooth/commit/9175b1698c08c7b99f1f16eb824378705490e346

<details><summary>CLICK ME TO SEE THE SCREENSHOTS</summary>

<b>Start Page</b>

<img src="https://user-images.githubusercontent.com/6080900/68541466-2fcf8000-03a0-11ea-8a97-eeb7a681f425.png">

<b>Admin Panel</b>

<img src="https://user-images.githubusercontent.com/6080900/68543477-dc692c00-03b7-11ea-9460-c9e5616d25c7.png">

<b>Result Page</b>

<img src="https://user-images.githubusercontent.com/6080900/68541784-18929180-03a4-11ea-8c37-b372a91d5b34.png">

<b>Gallery</b>

<img src="https://user-images.githubusercontent.com/6080900/68543476-dc692c00-03b7-11ea-8660-9052c25a43ff.png">

<img src="https://user-images.githubusercontent.com/6080900/68543475-dc692c00-03b7-11ea-8363-9288718b1e91.png">
</details>

**Comment by andi34** [comment]
@obkram i've applied your change to `resources/sass/partials/_button.scss ` 
https://github.com/andi34/photobooth/commit/0cb1141a5d39d197c4bf7d50cd6aeed93571943c

![Screenshot_2019-11-09_10-06-30](https://user-images.githubusercontent.com/6080900/68526160-3c3cd580-02d9-11ea-9ae8-d15ec8fb7f0a.png)

![Screenshot_2019-11-09_10-06-05](https://user-images.githubusercontent.com/6080900/68526161-3fd05c80-02d9-11ea-9d62-4fcb7b41188f.png)

![Screenshot_2019-11-09_10-09-03](https://user-images.githubusercontent.com/6080900/68526157-3810b800-02d9-11ea-9d7b-4422b0418725.png)

I've not touched the reset and save button in admin panel, does not look that good imo:

![Screenshot_2019-11-09_10-06-47](https://user-images.githubusercontent.com/6080900/68526168-5aa2d100-02d9-11ea-9754-54450f6b6f2a.png)

![Screenshot_2019-11-09_10-06-42](https://user-images.githubusercontent.com/6080900/68526169-5aa2d100-02d9-11ea-8b36-334e8e66538d.png)

**Comment by obkram** [comment]
@andi34 Vielen Dank für die Integragtion.

**Comment by andi34** [comment]
Nur auf meinem fork in einem branch ;)

**Comment by obkram** [comment]
@andi34 was Branches, Cherry Picks und solche Sachen angeht da bin ich ehr ein absoluter Muggel, aber es klappt doch immer irgendwie ;). Schönes Wochenende zusammen.

**Comment by andi34** [comment]
Round edges in Admin Panel:
https://github.com/andi34/photobooth/commit/2979af0ea64818127eadbb1bdbb31d6283886985

![Screenshot_2019-11-10_09-47-24](https://user-images.githubusercontent.com/6080900/68541398-36112c80-039f-11ea-89e7-6536fc3f343e.png)

**Comment by andi34** [comment]
https://github.com/andi34/photobooth/commit/15bdc244eff3621b35a249ade301ce0efa5d0872

![Screenshot_2019-11-10_09-54-22](https://user-images.githubusercontent.com/6080900/68541466-2fcf8000-03a0-11ea-8a97-eeb7a681f425.png)

**Comment by obkram** [comment]
@andi34 Das sieht großartig aus!

**Comment by andi34** [comment]
And some space between the buttons on the result page:
https://github.com/andi34/photobooth/commit/94f6e2f0f638d5723dfeca48c4910565ae8595e3

![Screenshot_2019-11-10_10-22-51](https://user-images.githubusercontent.com/6080900/68541784-18929180-03a4-11ea-8c37-b372a91d5b34.png)

**Comment by andi34** [comment]
Adjusted Admin Panel & close/reload button in Gallery

https://github.com/andi34/photobooth/commit/3c1ef3ae510ba04658817ae2c604e23f8c2d338c

https://github.com/andi34/photobooth/commit/9175b1698c08c7b99f1f16eb824378705490e346

![Screenshot_2019-11-10_12-42-36](https://user-images.githubusercontent.com/6080900/68543477-dc692c00-03b7-11ea-9460-c9e5616d25c7.png)

![Screenshot_2019-11-10_12-42-43](https://user-images.githubusercontent.com/6080900/68543476-dc692c00-03b7-11ea-8660-9052c25a43ff.png)

![Screenshot_2019-11-10_12-42-50](https://user-images.githubusercontent.com/6080900/68543475-dc692c00-03b7-11ea-8363-9288718b1e91.png)

**Comment by andi34** [comment]
**Look on mobile device (OnePlus 6)**

![Screenshot_20191110-124917](https://user-images.githubusercontent.com/6080900/68543560-df185100-03b8-11ea-9d05-c1453427f9de.jpg)

![Screenshot_20191110-124939](https://user-images.githubusercontent.com/6080900/68543561-e63f5f00-03b8-11ea-9405-a219c720ff47.jpg)

![Screenshot_20191110-125106](https://user-images.githubusercontent.com/6080900/68543565-f3f4e480-03b8-11ea-885b-6a73c26d3409.jpg)

![Screenshot_20191110-125033](https://user-images.githubusercontent.com/6080900/68543564-eb041300-03b8-11ea-9dd5-23c1b7d619ef.jpg)

![Screenshot_20191110-125056](https://user-images.githubusercontent.com/6080900/68543567-fc4d1f80-03b8-11ea-8c07-328cfab4d381.jpg)

**Comment by andi34** [comment]
Some adjustments to the Gallery button, looks better on the rounded corners:

![Screenshot_2019-11-13_16-53-19](https://user-images.githubusercontent.com/6080900/68780227-4989f500-0636-11ea-9098-ad99362d71ef.png)

**Comment by sualko** [comment]
I'm not a fan of round corners, but if that's common sense we can merge it anyway. One remark: Can you try to make only the outer corners round? So have no border radius at the edges between two buttons. Also only a round corner on the bottom right corner of the gallery button. Just an idea as kind of a compromise :-).

**Comment by andi34** [comment]
@sualko not sure if we should merge it. Just kept it here for other people.

Since I am learning css still, can you tell how to make only one side rounded?

**Comment by rawbertp** [comment]
I'm not a big fan of rounded corners/buttons too... Didn't all major UIs get rid of them in favour of flat, rectangular buttons/tiles? Anyways... if they have to be rounded, maybe the following can be used as inspiration: https://mdbootstrap.com/docs/angular/components/buttons/

**Comment by andi34** [comment]
Don't worry, it's not a must have. I've just played around with what @obkram started with.

Maybe someone has an idea on how to make it an config option?

**Comment by sualko** [comment]
> can you tell how to make only one side rounded?

https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius

> Maybe someone has an idea on how to make it an config option?

We could ship different templates (css files) and add a switch to choose which css file should be used. For me this is no priority.
