### ISSUE TITLE
Make collage more variable

### ISSUE THREAD

**Issue by chris883773** [andreknieriem/photobooth#189]
Hello,

at this time the collage takes 4 Photos. 
Now in other photobooth you can choose hove much photos are printed at x and y. 

For example you can take 1 picture at the left and 2 pictures at the right. 

![image](https://user-images.githubusercontent.com/50053446/68476257-86b34900-022a-11ea-9aed-68272ca2f8dd.png)

Maybe as admin you can change this in config. (collage_x and collage_y)

hope you enjoy and have a great day.

**Comment by andi34** [comment]
https://github.com/andreknieriem/photobooth/issues/164

https://github.com/andreknieriem/photobooth/issues/163
