### ISSUE TITLE
Update installation procedure:

### ISSUE THREAD

**Issue by DigiOrti** [andreknieriem/photobooth#19]
**Set up for Raspbian Stretch:**
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install apache2 -y
sudo apt-get install  php -y
sudo apt-get install php-gd -y
sudo apt-get install gphoto2 -y
sudo apt-get install libav-tools -y
cd /var/www/
sudo rm -r html/
sudo git clone https://github.com/andreknieriem/photobooth
sudo mv photobooth html

**Configure config.inc.php:**
sudo nano /var/www/html/config.inc.php
change to
$config['dev'] = false; 

**Rights:**
sudo chown -R pi: /var/www/
sudo chmod -R 777 /var/www
sudo nano /etc/sudoers
--> Add the following:
www-data ALL=(ALL) NOPASSWD: ALL
sudo reboot

**Ensure that the camera trigger works:**
sudo rm /usr/share/dbus-1/services/org.gtk.vsf.GPhoto2VolumeMonitor.service
sudo rm /usr/share/gvfs/mounts/gphoto2.mount
sudo rm /usr/share/gvfs/remote-volume-monitors/gphoto2.monitor
sudo rm /usr/lib/gvfs/gvfs-gphoto2-volume-monitor

**Enable the printer:**
Install CUPS: [https://www.elektronik-kompendium.de/sites/raspberry-pi/2007081.htm](url)
(Configure config.inc.php)
sudo nano /var/www/html/config.inc.php
>Example for Canon Selphy CP1300

$config['print']['cmd'] = 'sudo lp -d PRINTERnameINcups -o landscape -o media=Custom.100x148mm -o fit-to-page %s';

CP1300 as for now only works as a USB-printer with a wired connection. Elsewise you get an data-error on the printer screen.
So please search for a USB connection and use the CP910 printer driver in CUPS.

**Comment by Seilafeh** [comment]
+1 der dev Modus in der config ist fies :-D Habe mir ewig den Kopf zerbrochen, wieso die Kamera nicht auslöst, bis ich die Option entdeckt habe.

**Comment by thymon13** [comment]
> So please search for a USB connection and use the CP910 printer driver in CUPS.

How please ?

**Comment by thymon13** [comment]
I use Canon CP1300 but I can not launch a second impression until the previous one is finished. Otherwise the printer crashes ... :(


Do you know how to do it ?
