### ISSUE TITLE
Filter after taking photo

### ISSUE THREAD

**Issue by chris883773** [andreknieriem/photobooth#190]
Hi,

filter changes of the picture after doing this. 

**For example**
![image](https://user-images.githubusercontent.com/50053446/68476399-de51b480-022a-11ea-8503-a694c01c488f.png)

**Procedure**
Take a picture
Choose a filter
Save picture as "normal" and with filter (maybe you can choose this at config)
Adding picture at collage or at normal photos
Optional: Printing per button

Have a nice day!

**Comment by andi34** [comment]
Waiting for your Pullrequest. :)
Closing since duplicate https://github.com/andreknieriem/photobooth/issues/96

**Comment by andi34** [comment]
> Save picture as "normal" and with filter (maybe you can choose this at config)

Btw. If a filter is applied the original image stays in /data/tmp but isn't used by the gallery

**Comment by rawbertp** [comment]
> Closing since duplicate #96

Is this really a dup? In #96 @sualko mentioned to show a(ny) preview. The request here, like my comment in #96, is to apply the filter to the actual photo.

**Comment by andi34** [comment]
Since the general topic in https://github.com/andreknieriem/photobooth/issues/96 is to enhance the filter implementation in the whole process I'd say it is a duplicate. Can be reopened if I am wrong.

**Comment by chris883773** [comment]
> > Closing since duplicate #96
> 
> Is this really a dup? In #96 @sualko mentioned to show a(ny) preview (to my understanding this could be just a random sample picture). The request here, like my comment in #96, is to apply the filter to the actual photo.

That is true. I want to take a picture. And after taking a picture choosing the filter. 
Than take a new picture with button.

**Comment by rawbertp** [comment]
@chris883773 You might want to have a look at the linked PR #196

**Comment by chris883773** [comment]
That is what i am looking for. 

> @chris883773 You might want to have a look at the linked PR #196

**Comment by andi34** [comment]
```
sudo -u www-data -s
cd /var/www/html
git pull https://github.com/rawbertp/photobooth rp-filter-pic
exit
```
