### ISSUE TITLE
Frage zur Liveview

### ISSUE THREAD

**Issue by mdkhome** [andreknieriem/photobooth#197]
Hallo, ich nutze Raspi 3b + und habe das Installastionscript vom Wiki genommen um Photobooth zu installieren. Habe die PiCam angeschlossen und auch in der Raspi-Config freigegeben. Sie funktioniert.
Aber ich bekomme kein Vorschau angezeigt. Muss noch was extra geändert werden. Da in /admin ja der Hacken aktivert wurde für (Vorschau) gehe ich davon aus das es eigentlich laufen sollte.
Als System läuft Buster. Bin nicht sehr bewandert im Bereich Linux/Dabian deswegen hoffe ich auch einfache Ratschläge :)

Ich bedanke mich schonmal im Vorraus

**Comment by andi34** [comment]
Wenn du auf Take Pic clickst siehst du eine Vorschau.

**Comment by mdkhome** [comment]
Genau das passiert nicht bekomme einen weißen Hintergrund und den countdown dann macht er das Foto auf meiner Canon via USB. Das Bild zeigt er mir auch an. Aber ein livebild nicht.

**Comment by andi34** [comment]
Livepreview geht mit der Pi Cam

**Comment by mdkhome** [comment]
Also versteh ich das richtig, Das Foto machen mit der Canon und gleichzeitig das Liveview von der Pi Cam geht nicht ?
Hatte am Anfang die Pi Cam laufen und da hatte ich auch kein Live Bild gesehen beim Auslösen

**Comment by andi34** [comment]
Funktioniert bei mir einwandfrei.
https://github.com/andreknieriem/photobooth/wiki/FAQ#is-pi-camera-supported
