### ISSUE TITLE
Delete Images in Gallery

### ISSUE THREAD

**Issue by strunki** [andreknieriem/photobooth#204]
Hey Guys,

first of all, big thanks for creating this nice Photobooth. 
The issue I'm struggling with is deleting images (well I deleted the images but the links to them are still there). Is there any solution so that I'm able to clear the gallery for the next event?

Big Thanks in advance,
strunki

**Comment by andi34** [comment]
Check the `db.txt` in your data folder.

You could simply change `$config['folders']['data'] = 'data';` to a different name.

**Comment by strunki** [comment]
Thank you, that did it for me!
