### ISSUE TITLE
Countdown Live View

### ISSUE THREAD

**Issue by Pfmarc112** [andreknieriem/photobooth#209]
Can anybody please explain me, how i can change the Countdown Display, so that the live view in the background can be seen?
In the FAQ it says to change the blur, but i don‘t know how.
Thank you in advance and best regards!

**Comment by andi34** [comment]
Enable preview by device cam and use raspberry camera. You need to access Photobooth as localhost/127.0.0.1

You can only use a tablet/Mobile phone cam if you setup your server to use https.
