### ISSUE TITLE
Croma Key saving without finishing saving

### ISSUE THREAD

**Issue by Joeol** [andreknieriem/photobooth#213]
Hallo, ich habe mir mit der Photobooth Software einen Raspberry Pi 4 4 GB eingerichtet. Der Raspberry macht alles, den Wlan AP, den Webserver und das Frontend.  An dem Raspberry habe ich einen 15" Touchscreen Monitor. Es läuft alles top und auch recht zügig, selbst das Livebild über die PI Camera, nur beim Croma Key habe ich das Problem, dass das Bild nicht gespeichert wird, sondern der Screen immer auf "speichern" steht. Ich habe im Chrom schon den entsprechenden Flag, wie beschrieben, disabled, jedoch will es einfach nicht funktionieren. Vielleicht hat ja jemand einen Hinweis für mich, was ich falsch mache.
Vg
Jörg

**Comment by andi34** [comment]
Mal mit F12 in die Console Des browsers geschaut?

**Comment by Joeol** [comment]
Ja, schon, leider kann ich das nicht interpretieren, bin mehr der Schrauber als der Programmierer.

**Comment by andi34** [comment]
Schreit er denn mit irgendeinem Fehler?
Kannst auch Screenshot hier Posten

**Comment by andi34** [comment]
Funktioniert es mit einem Foto dev mode?

Wenn ja, schraub Mal die Bildgröße in der kamera runter.

**Comment by andi34** [comment]
Ok, kann ich nachvollziehen.

![Screenshot_20191230-203233](https://user-images.githubusercontent.com/6080900/71597464-873dd100-2b43-11ea-98fa-6b4f111e738a.jpg)

**Comment by andi34** [comment]
https://datanextsolutions.com/blog/how-to-fix-nginx-413-request-entity-too-large-error/

**Comment by Joeol** [comment]
Ich bekomme in "Console" die Fehler
Failed to load resource: the server responded with a status  /favicon.ico:1
 of 404 (not Found)
Failed to Load recource: the Server responded /api/chromakeying/save.php:1 
with a status of 413 (request Entity Too Large)
Die Bildgrösse habe ich mal runtergstellt, dass Ergebnis ist das Selbe.

**Comment by Joeol** [comment]
Ok, schaue ich mir an, probiere ich aus und melde dann Erfolg, vielen Dank für die Hilfe.

**Comment by andi34** [comment]
Funktioniert. Einfach dem Link folgen und entsprechend die nginx Config ändern.

![Screenshot_20191230-205118](https://user-images.githubusercontent.com/6080900/71598215-409da600-2b46-11ea-8ad0-6faea747ebff.jpg)

**Comment by Joeol** [comment]
Läuft, vielen Dank für die Hilfe.
