### ISSUE TITLE
Simple way to set Exposure of RPi Cam

### ISSUE THREAD

**Issue by LDFOTO** [andreknieriem/photobooth#216]
Preview of RPi cam is too dark

Maybe it is possible to set it to auto exposure or add a method to set parameters for given lighting situation.

**Comment by andi34** [comment]
It's a stream using the device cam and there's nothing changed by Photobooth on default brightness/exposure. It's using default values, not sure if you can adjust them.

**Comment by LDFOTO** [comment]
Ok. Isn't there any configuration file for cheese?

**Comment by andi34** [comment]
The cheese text ist added after the countdown, time "cheese" is visible can be adjusted.

**Comment by LDFOTO** [comment]
How do I adjust exposure?

**Comment by andi34** [comment]
Settings for the stream:
https://github.com/andreknieriem/photobooth/blob/18c07f2/resources/js/core.js#L11-L17

Start and stop the stream:
https://github.com/andreknieriem/photobooth/blob/18c07f2/resources/js/core.js#L97-L126

This gets called here to start the stream once you click on take picture button:
https://github.com/andreknieriem/photobooth/blob/18c07f2/resources/js/core.js#L137

Stopped here https://github.com/andreknieriem/photobooth/blob/18c07f2/resources/js/core.js#L173 right before the picture is taken.

Cheese text is added here https://github.com/andreknieriem/photobooth/blob/18c07f2/resources/js/core.js#L155

**Comment by LDFOTO** [comment]
I went to Cheese project page. Can't find anything on exposure settings.

**Comment by andi34** [comment]
You could try changing https://github.com/andreknieriem/photobooth/blob/master/resources/sass/style.scss#L95

From `background: rgba(255,255,255,0.9);` to `background: #ffffff;`

And see if it makes a difference. Make sure running `yarn build` after changing the sccs file

**Comment by LDFOTO** [comment]
thx. I'll try on Friday and will report

**Comment by andi34** [comment]
👍 that's the only thing I can think of which could make a difference, else there's no way I know.

**Comment by LDFOTO** [comment]
I can see no change. Is it possible to use an alternative to cheese?

**Comment by andi34** [comment]
There's nothing changed by Photobooth besides the opacity from cheese which could make the preview a bit dark.

You'll have to dig around and see if you can change it inside Raspbian by default then.

You can change the cheese text inside the language file. Not sure what you like to change.

**Comment by LDFOTO** [comment]
First I thought Raspicam is controlled by raspivivid which allows several settings on exposure. Can't find anything on how cheese is controlling exposure. Seems to be a fixed setting.

**Comment by LDFOTO** [comment]
Raspicam seems to have no auto exposure feature by itself. Specification says "controlled by ISP"

**Comment by andi34** [comment]
We're only accessing the device cam in the Webinterface, therefore Default Parameter from PiCamera library are used and I don't know a way you could change it.

**Comment by LDFOTO** [comment]
There seems to be no way to solve this. thx

**Comment by andi34** [comment]
You could try adding `filter:brightness(400%);` in the style.scss for the video

https://github.com/andreknieriem/photobooth/blob/master/resources/sass/style.scss#L339

Change:
```
#video {
  position: absolute;
  top: 50%;
  margin-top: -240px;
  margin-left: -360px;
  left: 50%;
}
```
To
```
#video {
  position: absolute;
  top: 50%;
  margin-top: -240px;
  margin-left: -360px;
  left: 50%;
  filter:brightness(400%);
}
```
