### ISSUE TITLE
Create responsive design

### ISSUE THREAD

**Issue by mhellmeier** [andreknieriem/photobooth#22]
The UI looks really nice on a desktop pc. I tried it on my phone and some tablets but it looks bad there. I want to use the webinterface with a tablet in the real fotobox.

**Design Problems**:
- "Creating foto"-button in the middle of the text on the front page
-  Width / Height of the hole site is wrong (I can scroll left / right or up / down on my mobile devices)
-  Gallery to small or rather only on a half screen
-  QR Code to big on mobile devices in landscape mode
-  Various bugs after rotating the phone / tablet

**Comment by BrixSat** [comment]
Thanks :) will try to improve it. 

Can you please share the tablet model and a real picture of the photo-booth?

Thanks in advance.

**Comment by andreknieriem** [comment]
Hey BrixSat, thanks for your help! Will you add a pull request?

**Comment by mhellmeier** [comment]
> Can you please share the tablet model and a real picture of the photo-booth?
Yes of corse! I am using a Nexus 7 tablet. The photo-booth isn't finished so I can't show you a real-world picture of it. But I want to put the Nexus 7 tablet in landscape mode into the box. I will add some screenshots - hope it helps!

> The browser you are using on the tablet?
I am using Google Chrome (shipped with Android)

You can also reproduce the design failtures with the Google Chrome desktop version.

![photobooth-1](https://user-images.githubusercontent.com/1036284/36804488-065bb018-1cbb-11e8-819c-02e2a8233aef.png)

![photobooth-2](https://user-images.githubusercontent.com/1036284/36804491-0adf4a82-1cbb-11e8-8fe9-fc9aa7372e67.png)

![photobooth-3](https://user-images.githubusercontent.com/1036284/36804497-0de7b782-1cbb-11e8-94fe-219a6e3ea63c.png)

**Comment by F4bsi** [comment]
@BrixSat 
Hey, 
I couldn't find any changes to the design in your repository, so I started to work on it. I hope that's ok? :-)

**Comment by BrixSat** [comment]
Go for it :)

**Comment by F4bsi** [comment]
Submitted #24 to fix this issue. 
Maybe you could try it out?

**Comment by andi34** [comment]
You could cherry-pick:
https://github.com/andi34/photobooth/commit/d317f58d95752ac585c8e2545ef24957ceb11a4c

https://github.com/andi34/photobooth/commit/9dab3dfae43342952ba5f6db85c5123aa3869c0b

And

https://github.com/andi34/photobooth/commit/250172ae175e6f815375335dcce566b840ad7bb2

Hope it helps.
