### ISSUE TITLE
Picture copy to USB Stick 

### ISSUE THREAD

**Issue by Seppel0815** [andreknieriem/photobooth#224]
Hey. Thanks for the wonderfull Photobooth-Tool and the Energy and time you Spend in this Projekt. 

In my opinion it is a good idea if we have the option to mount a USB stick and copy the pictures onto it. - so that we can give the usb stick directly to the married couple.

My idea is:
A new admin menu where you can see the number of images in the folders, the size of the folder and a button to mount/unmount a USB stick and copy the Field on it.

**Comment by andi34** [comment]
Not sure why always the template is ignored :disappointed: 

But maybe a hint for you how to do such in background without admin menu
https://github.com/kcinnaySte/photobooth/commit/228d27ecc42cdf0e76ef3708f03a2e38eee22357

**Comment by andi34** [comment]
You could try if using a symlink as data folder works for you. Create a `data` folder on your USB stick.
```
sudo -u www-data -s
cd /var/www/html
mv data databackup
ln -s /stick/data data
exit
sudo chown -R www-data:www-data /stick/data
```
(/stick/data can be adjusted to your mount point)

**Comment by Exalik** [comment]
Hello,

Thank's for your help. I do not have success to copy pictures on an usb stick but I used a 32Gb micro sd card and it was enough.

Today, I would like to download all the pictures taken during the weeding but I don't find them on the card.... can somebody please tell me where they are ???


Olivier
