### ISSUE TITLE
Button löst nicht aus (GPIO)

### ISSUE THREAD

**Issue by stoffl6781** [andreknieriem/photobooth#225]
Hallo zusammen,
der Button auf PGIO 24 löst kein Bild aus. 
Wenn ich die button.py öffne (mit sudo python button.py) --> sehe ich, dass wenn der Button geschlossen wird, eine "Auslösung" erkannt wird. (habe dazu in der while das echo auskommentiert). 
Dies funktioniert aber genau nur 1x mal, beim erneuten Drücken, wird es nicht mehr getriggert. 

Eine manuelle Auslösung am Touch ist möglich und funktioniert. 
Eine Auslösung mit der "enter" Taste funktioniert auch. (13). lt. Wiki. 
Crontab mit sudo user eingerichtet. 

Kann das ein "rechte" Problem sein? 
Wo suche ich da?
Danke
Stoffl 

**Photobooth**
- Did it work before? [no]
- Which version of Photobooth are you using? latest

RPI Mini, Canon EOS 550

**Comment by andi34** [comment]
Solved? If yes, what has been the solution?
