### ISSUE TITLE
No Picture taken after Cheeeese with Livewallpaper 

### ISSUE THREAD

**Issue by eierbatz** [andreknieriem/photobooth#231]
Hallo, danke für die Anwendung an den Entwickler , super Sache.

Mein Problem:
Ich habe Photobooth2.2.1.zip von den Isues kopiert und auf mein Rasp kopiert. Funktioniert soweit. 
Livewallpaper funktioniert über die Tabletcam bei dem Homescreen und auch bei dem Countdown. Aber nach dem Cheeese wird kein Bild aufgenommen und ein Fehler ausgegeben.
Deaktiviere ich das Livewallpaper während dem Countdown funktioniert wieder die Aufnahme.

Ich würde gerne das Livebild während dem Countdown verwenden, damit die Fotomodelle sich in der Zeit korrekt ausrichten können.

Kann ich irgendwelche Logfiles genererieren oder auslesen, die mir hinweise geben was bei der Fotoaufnahme schief läuft?

Danke

**Comment by andi34** [comment]
Falsches Repo. Bitte issue in meinen Fork, da die Funktion hier gar nicht zur Verfügung steht.
Bitte das Issue Template beachten, dann schaue ich mir das gerne an.
