### ISSUE TITLE
How to set-up without USB connection to camera

### ISSUE THREAD

**Issue by fisk3110** [andreknieriem/photobooth#236]
**Describe the bug**
Not directly a bug: I tried to cuse wifi remote control for my Sony Apla 7 II.
But I was not able to connect.

Is it in general possible to get your booth working with wifi cameras?

**Comment by andi34** [comment]
You can use any program which can be used via command line. Not sure if gPhoto2 supports wifi connections.

Or is it about triggering the photo?
Therefore check https://github.com/andreknieriem/photobooth/blob/19780ee527f5d8d17666f3f18115665e797a2830/config/config.inc.php#L50-L53

Cheap Bluetooth/IR Presenter should work fine.

I am using this one:
![Screenshot_20200408-102420](https://user-images.githubusercontent.com/6080900/78761648-2d8b4500-7983-11ea-9ec0-571fa42ae90b.jpg)

**Comment by sualko** [comment]
According to a [german article](https://www.multimedia4linux.de/index.php/canon-dslr-wiki/wlan-wi-fi-mit-gphoto2-nutzen) this should be possible with `gphoto2 --port ptpip:CAMERA_IP`.
