### ISSUE TITLE
Live view (Question)

### ISSUE THREAD

**Issue by stefanbrunner** [andreknieriem/photobooth#239]
Hallo,
I have installed the software and basically works.
But, do I understand correctly with the preview, in order to see a preview during the coundown, I have to use a webcam next to the photo camera?
It is not possible to get the live view trough the photo camera..?

Thanks for your hints.

**Comment by andi34** [comment]
Right, e.g. use Raspberry Pi Camera module.

**Comment by andi34** [comment]
https://github.com/andreknieriem/photobooth/wiki/FAQ#preview-by-device-cam

https://github.com/andreknieriem/photobooth/wiki/FAQ#can-i-use-a-live-stream-as-background
