### ISSUE TITLE
Name images in a consecutive way, like adding 0001, 0002 etc.

### ISSUE THREAD

**Issue by florianmueller** [andreknieriem/photobooth#247]
**Is your feature request related to a problem? Please describe.**
After finishing my first photobooth project I am very happy with this github project. You guys did an amazing job! And because I tested it already on some partys, I think I might have some useful additions: If you copy the images later from the photobox to somewhere, you end up with that random naming that only allows to see the images in a good order by sorting them by creation date in time. I would love to have the option to save the pictures in a consecutive way by lets say "partyimg_00001" and ongoing. Some applications like dropbox can't display images by date created in a shared link folder (without being looged in).

**Describe the solution you'd like**
Add option to admin interface to name the images in data/images in a more structured consecutive way.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by andi34** [comment]
https://github.com/andi34/photobooth/commit/dab9f606790addca9a5036149e97aed5f3c0d9a4

https://github.com/andi34/photobooth/commit/2bf666936f98d10ff376b55f24631fd5d5643d9b
