### ISSUE TITLE
Preview from DSLR

### ISSUE THREAD

**Issue by Exalik** [andreknieriem/photobooth#250]
**Is your feature request related to a problem? Please describe.**
I have installed this photobooth software on an Orange Pi 3 board.
This board does not offer a camera connector and the pi camera does not take in account the flash luminosity.

**Describe the solution you'd like**
I would like to have a preview from the dslr

**Describe alternatives you've considered**
Using an usb camera but the preview will not take in account the flash luminosity

**Additional context**
N/A

**Comment by andi34** [comment]
Duplicate https://github.com/andreknieriem/photobooth/issues/242
