### ISSUE TITLE
Virtual Keyboard when sending an email

### ISSUE THREAD

**Issue by djtale** [andreknieriem/photobooth#252]
Hello,

Would it be possible to have a virtual keyboard displayed on the screen when the email feature is enabled and when the user has to type his email address ?

Thanks

**Comment by andi34** [comment]
You could try to implement https://virtual-keyboard.js.org/ maybe

**Comment by djtale** [comment]
Thanks, that would be a great improvement for touchscreens.
Can't wait to test it ;)

**Comment by andi34** [comment]
IMO a virtual keyboard should be handled OS side.
There's virtual keyboards available which can be used on PiOS.
