### ISSUE TITLE
Feature Request - Greenscreen keying

### ISSUE THREAD

**Issue by Taankydaanky** [andreknieriem/photobooth#26]
Hey,
I've startet on working for a greenscreen process. Did anybody of u try that before? I want the user to take a background, make the picture, switch the greenscreen with choosed background and print it.

**Comment by soko1988** [comment]
Hey @Taankydaanky,
whats the status of this amazing Feature? Do you build it?

**Comment by andi34** [comment]
Got some code (Thanks to André and Steffen) to test and play around.
Need some images which can be used as background to make it public, as atm I don't know if included background images are allowed to use.

Who got some own shot backgrounds (Walls for example) can upload here and tell that it's fine to use for this project.

**Comment by tobiashaas** [comment]
Moin Andi, 
Ich kann dir gerne welche zur Verfügung stellen! ;-)

**Comment by andi34** [comment]
Gerne hier anhängen oder senden an andi@unlegacy-android.org

**Comment by andi34** [comment]
https://fontawesome.com/v4.7.0/icon/magic
Nutze ich für Filter.

Würde für Greenscreen keying dieses nehmen:
https://fontawesome.com/v4.7.0/icon/paint-brush

Bessere idee jemand?
https://fontawesome.com/v4.7.0/icons/

**Comment by tobiashaas** [comment]
Fotos schicke ich dir gleich! 
Die Icons von Font-Awesome finde ich Super und die, die du dir herausgesucht hast auch. 
Sind passend! ;-)

**Comment by andi34** [comment]
https://github.com/andi34/photobooth/commits/private

Keying funktioniert, leider werden die Bilder nicht gespeichert... jemand eine idee?

Keying works, but pictures don't get saved... someone an idea?

**Comment by andi34** [comment]
Bilder werden nun gespeichert, aber nur, wenn kein Hintergrund gewaehlt wird.

Pictures get saved, only if no background is choosen.

**Comment by andi34** [comment]
Works now. But only on my Desktop PC. Guess the Pi performance is not enough to really use it.

**Comment by andi34** [comment]
an issue seems to be the picture size, need to investigate further
![20190804_131322](https://user-images.githubusercontent.com/6080900/62422891-f52bbc80-b6b9-11e9-8bd9-990d50160979.jpg)

**Comment by andi34** [comment]
Fixed https://github.com/andi34/photobooth/commit/d9e630583f9a8437650a3c9228281a8ece4ed963

And

https://github.com/andi34/photobooth/commit/f4571dab6fb07cf52c7f43759f1c1f02728fb98c
