### ISSUE TITLE
Blank Screen in Browser

### ISSUE THREAD

**Issue by Jhipsey** [andreknieriem/photobooth#263]
After installing the software from github everything on the pi seems to work fine, but I got a white screen in every browser I use. Header tab says "Photobooth" and a symbol of a camera next to it though. 

How can I fix this.?
![image](https://user-images.githubusercontent.com/78096327/106017400-b5803e00-60c0-11eb-9439-a761f361377f.png)

**Environment (please complete the following information):**
 - raspian lite (downloaded on January 27th, 2021)
 - each browser I tried (Chrome, IE, Firefox)

**Comment by andi34** [comment]
Seems like you're missing the css files which get generated while running `yarn build`

**Comment by Jhipsey** [comment]
Worked just fine today. Couldn´t find the problem, but it kind of solved itself
