### ISSUE TITLE
Couldn´t read JPEGS.

### ISSUE THREAD

**Issue by Jhipsey** [andreknieriem/photobooth#264]
After the countdown the following mistake comes out. For me seems like the software can´t deal with the photo.

Is there a command to solve this problem?

![grafik](https://user-images.githubusercontent.com/78096327/106103138-bf498600-6140-11eb-8368-1da32d400935.png)

**Environment (please complete the following information):**
 - Raspberry Pi OS Lite Kernel version 5.4
 - latest firefox browser
 - Rasperry cam V2

latest photobooth version: 2.1.0

**Comment by andi34** [comment]
Setup like described here? https://github.com/andreknieriem/photobooth/wiki/FAQ#is-pi-camera-supported

**Comment by andi34** [comment]
Please try on Photobooth v4. I am sure we'll find a solution if you still have trouble.
https://photoboothproject.github.io/Changelog
