### ISSUE TITLE
How to install an older version | "How to" eine ältere Version installieren

### ISSUE THREAD

**Issue by scapemaster** [andreknieriem/photobooth#266]
Hallo liebe Photoboxer,
wie hier [Issue 40](https://github.com/andreknieriem/photobooth/issues/40) beschrieben. Möcht ich auch gerne eine Photobox mit einer funktionierenden Version betreiben. 
Kurz eine Beschreibung des **Problems**: Photobooth 2.x.x funktioniert aktuell nicht auf einem Raspberry Pi und bis Dato gibt es noch keine Lösung des Problems. Das **Workaround** ist, eine ältere Version [Version 1.5.2](https://github.com/andreknieriem/photobooth/releases/tag/v1.5.2) zu verwenden.

Leider komme ich mit der Installation nicht ganz zurecht. Die Installation der "latest" ist denkbar einfach aber ein How-To für eine Vorgängerversion wäre echt hilfreich für mich!
Kann mir jmd dabei helfen?

Viele Dank, Andi

**Comment by andi34** [comment]
```
git fetch --all --tags
git checkout tags/v1.5.2
```
Aber bitte beachten, dass du dann ggf. auch die alten Anweisungen zur Nutzung befolgen musst (steht aber alles im readme):
https://github.com/andreknieriem/photobooth/tree/v1.5.2
