### ISSUE TITLE
Passport Photo Feature

### ISSUE THREAD

**Issue by S1M0NDOTCOM** [andreknieriem/photobooth#271]
I think that's a good feature. in addition, the project would have a larger target group

**Comment by fotokrauskopf** [comment]
Ihr wollt Euch nicht mit den Reklamationen der abgelehnten Bilder aus den Ämtern herum schlagen... Viele Grüße Marcel

**Comment by andi34** [comment]
@fotokrauskopf a 2x4 layout should be easy to add and I thought the same you told. Calling it "passport" should only mean the single picture size on the "collage" and not for official passport pictures.

I am about to look at it once I've finished working on a Photobooth integrated updater on my fork.

**Comment by andi34** [comment]
A custom collage Layout can be defined in Photobooth V4
https://photoboothproject.github.io/FAQ#how-can-setup-a-custom-collage-design
