### ISSUE TITLE
Absolute path in config

### ISSUE THREAD

**Issue by Matz3187** [andreknieriem/photobooth#283]
Hello Guys,

I have a problem with photobooth. I want so save pictures on USB drive. When I change the image path in config to an absolute path "/media/usbdrive" (mounted USB drive). photobooth will create a folder in wwwroot named media and inside folder usbdrive.

Is there any posibility to set image path to an absolute path.

Kind Regards
Matthias

**Comment by andi34** [comment]
Not tested, but might work.
```
sudo mv  /var/www/html/data/images  /var/www/html/data/images-bak
ln -s /var/www/html/data/images /media/usbdrive/
sudo chown -R www-data:www-data /var/www/
sudo chown -R www-data:www-data /media/usbdrive/
```

Else the file sync feature inside my Photobooth v3 release might be interesting for you: https://github.com/andi34/photobooth/releases/tag/v3.0.0

**Comment by Matz3187** [comment]
Thank you :)

This solution worked for me.

Kind Regards 
Matthias
