### ISSUE TITLE
Button too small with German language

### ISSUE THREAD

**Issue by der1igedon** [andreknieriem/photobooth#285]
If I change the language to German and take a collage the text doesn't fit on the buttons (for nextPhoto for example). It looks like this: 

![IMG_7439](https://user-images.githubusercontent.com/21998742/127772559-13238f11-b5da-4fe3-8222-9a5af2eb7b38.jpg)

Does anyone has an idea how to adjust the button sizes or is this probably related to using umlauts with CSS?

Thank you for your help!
Best regards

**Comment by andi34** [comment]
https://github.com/andreknieriem/photobooth/pull/281
