### ISSUE TITLE
Gallery picture import

### ISSUE THREAD

**Issue by HappySeppel** [andreknieriem/photobooth#286]
Hello @andreknieriem and others,

is there a way to import pictures in the gallery so that the "database" known that a new picture is arrived in the picture folder? Especially when no photo is taken by it self.

I want to use an other raspberry to view all the pictures witch are taken by an other photobooth.

Has anybody an idear?

**Comment by andi34** [comment]
Hey! This sounds like you want to use a own gallery and not the Photobooth itself.
You'd better look at a lightbox, e.g. https://github.com/andreknieriem/simplelightbox .

On Photobooth we're using https://github.com/dimsemenov/PhotoSwipe

Other solutions would be you disable the database and read the files from the folder instead, on a lot of pictures this might reduce the performance.
Example: https://github.com/andi34/photobooth/commit/f89982c9ccc837b7994c57f384f5f23c09de4606

Best regards

Andi
