### ISSUE TITLE
Could not read jpeg file. Are you taking raws?

### ISSUE THREAD

**Issue by jonkoss** [andreknieriem/photobooth#290]
Could not read jpeg file. Are you taking raws?

I'm getting the above error everytime I'm taking a shot. Any idea why that is happening?

**Comment by Jing-King** [comment]
I got the same error, I fixed it by removing the raw setting from the camera. The camera I am using is a canon EOS M3.
https://www.youtube.com/watch?v=7twg3SEJFC0

**Comment by andi34** [comment]
GPhoto2 often doesn't like if wifi is enabled on a camera.
Like mentioned another reason, set to jpeg only inside your camera.
