### ISSUE TITLE
device cam preview broken after upgrade from 2.x version

### ISSUE THREAD

**Issue by black-snake** [andreknieriem/photobooth#296]
**Describe the bug**
After I upgraded to the latest version by `git checkout origin/master` the device preview (Raspberry Camera v2) does not longer work. Even a reset of the settings (also tried `reset-raspbian.sh`) does not fix the issue.

**To Reproduce**
1. Upgrade via https://github.com/andreknieriem/photobooth/wiki/Update-Photobooth
2. Try to take a picture in Chromium with exception in `unsafely-treat-insecure-origin-as-secure`. (preview picture not displayed, only countdown, no asking for permission to access webcam by Chromium)

**Expected behavior**
A preview from the device cam is displayed. Chromium asks for permission to access webcam.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Raspbian 10 (buster)
 - Browser: Chromium
 - Version: 90.0.4430.212 (Developer Build)

**Photobooth**
- Did it work before? yes
- Which version of Photobooth are you using? newest from origin/master (can't find version string anywhere)

**Additional context**
N/A

**Comment by black-snake** [comment]
Thanks for the reply. I finally found the issue! It‘s been the latest version of Chromium (v92) which causes the device camera access to stop working. From this version of Chromium on, my Raspberry Pi Cam v2 is no longer recognized as camera by the browser. I will file a respective issue for Chromium.

**Comment by Domanaik** [comment]
@black-snake can you confirm on which older version is was running for sure? Im currently using v90.0.4430.212 and it looks like I have the same problem.

**Comment by black-snake** [comment]
> @black-snake can you confirm on which older version is was running for sure? Im currently using v90.0.4430.212 and it looks like I have the same problem.

Hey, I currently don’t have access to my photo booth, so I can tell you the exact version of chromium at the moment. However, are used pi apps to downgrade chromium. Take a look at these links below:

- https://forums.raspberrypi.com/viewtopic.php?t=290329
- https://forums.raspberrypi.com/viewtopic.php?t=290329

You downgrade version by version starting from the newest one and test each version for camera functionality.

@andi34 I don’t know if it’s a kernel issue — could be. Yet, at the time of writing my original post, I upgraded the system to all newest available versions (including the kernel) and I experienced that the camera worked in chromium when I downgraded chromium only.

I am a bit short of time at the moment so I’m sorry that I can’t go into more detail at this point. But please keep us posted on what you tried and what might have solve the issue.

**Comment by Domanaik** [comment]
I tested it with Piapps > Downgrade Chromium to v88 and its working again. Thanks for the help!

**Comment by black-snake** [comment]
> I tested it with Piapps > Downgrade Chromium to v88 and its working again. Thanks for the help!

Great to hear, could you maybe file a chromium issue?

**Comment by andi34** [comment]
> (...) Now you've explained that you are on buster it all makes a bit more sense. Buster _does_ have a working camera V4L2 layer and v88 works with that, something got broken in Chrome after that going to v92 (probably "better" size checking), but then bullseye came out and the policy decision was that new versions of Chrome would only be ported to bullseye (it was getting to be an increasing pain to get a compatible lib set to compile on buster), buster would get the base debian port which doesn't have my V4L2 size kludge in it (v95 bullseye does). This decision does have the unfortunate side effect that, as the V4L2 camera driver is bust in bullseye (or it was last I looked - it may have got better) and libcamera is currently problematic that Pi camera support is bust everywhere :-( That isn't a helpful response I know, but I believe it to be a statement of where we are.

So there's only the way of self-compiling chromium to use a newer version than v88.
I'll try to dig into it if I find enough time.

**Comment by black-snake** [comment]
Thank you so much for engaging yourself into that. As soon as I have the time, I will try this with a fresh bullseye version of Raspbian and the latest version of Chromium.

**Comment by black-snake** [comment]
So, I just conducted some research with the following setup:

- Raspberry Pi 3
- Raspberry Pi Cam v2
- fresh and unmodified installation latest Raspbian (Debian Bullseye-based), just installed all available updates via `apt-get`

Here are my findings:

1. By default, the new Raspbian distribution comes with `libcamera` as a replacement for `raspistill` (`libcamera` is incompatible with the way `raspistill` works).
2. When I started Chromium with a fresh updated installation relying on `libcamera`, Chromium asked for permission to access the camera but I couldn't get video from the camera to be displayed. So I went a more basic approach and tried to use `libcamera-hello` as test preview to see if the camera is detected and works in general. This fails with an error something like `failed to import fd 19` -- same for `libcamera-still -o test.jpeg`. Yet, `libcamera-still -o test.jpeg -n` (`-n` is for no preview) works. I googled the error but couldn't find any solution to resolve the issue. Is this something related to the video driver because it does work without displaying (previewing) the camera image(s).
3. I switch to legacy camera interface via `sudo raspi-config` and got it working in Chromium instantaneously. Also `raspistill` works. However, `raspistill` and its variants are deprecated. So this does not seem to be a very future-proof way.

I can't understand why `libcamera-hello` does not work out-of-the-box with a fresh and clean installation of Raspbian using the original Raspberry Pi Camera v2.

Anyways, I you can live with the legacy interface for the camera, you're good to go with Raspbian (Bullseye) and the current version of Chromium.

**Comment by andi34** [comment]
Thanks for your feedback!

The information I got sounds like there's still problems with the driver on bullseye

> (...) as the V4L2 camera driver is bust in bullseye (or it was last I looked - it may have got better) and libcamera is currently problematic that Pi camera support is bust everywhere :-( (...)

**Comment by andi34** [comment]
Just to mention:
Pi Camera you might need a `dtoverlay` to be set manually (on Pi3 and older from whats written here https://pi-buch.info/fotos-und-videos-mit-den-libcamera-tools-aufnehmen/).
Also see:
https://www.raspberrypi.com/documentation/accessories/camera.html#if-you-do-need-to-alter-the-configuration

**Comment by andi34** [comment]
Downgrade Chromium on Buster
```sh
wget "http://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/chromium-browser_88.0.4324.187-rpt1_armhf.deb"
wget "http://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/chromium-codecs-ffmpeg-extra_88.0.4324.187-rpt1_armhf.deb"
sudo apt install --no-install-recommends --allow-downgrades --allow-change-held-packages ./chromium-browser_88.0.4324.187-rpt1_armhf.deb ./chromium-codecs-ffmpeg-extra_88.0.4324.187-rpt1_armhf.deb
sudo apt-mark hold chromium-browser chromium-codecs-ffmpeg-extra
```
