### ISSUE TITLE
Chroma Keyring

### ISSUE THREAD

**Issue by jonkoss** [andreknieriem/photobooth#298]
Gibt es eine Anleitung zum Chroma Keyring? Im Wiki habe ich leider nichts gefunden.

**Comment by andi34** [comment]
Eine wirkliche Anleitung braucht es eigentlich nicht denke ich, da das Feature ziemlich selbsterklärend ist und du nicht wirklich etwas einstellen.

Wenn du's aktivierst kannst du über die Gallerie das Feature nutzen. Geht aber nur bei Foto-Aufnahmen, die mit aktiviertem Keying-Feature aufgenommen wurden. 

Grün wird rausgefiltert und du kannst den Hintergrund ersetzen. Die Hintergründe findest du unter resources/img/background im Pfad der Photobooth-Installation (beim hinzufügen neuer darauf achten, dass der www-data Nutzer des Systems die Datei lesen darf!).

Je nach Photobooth--Version kannst du zwischen 2 Varianten fürs keying wählen, beim Seriously.js könntest du sogar im Adminpanel den grünwert anpassen (somit z.B. auch bluescreen nutzen anstatt Greenscreen). Auch lässt sich je nach Photobooth--Version der Pfad zu den Hintergründen anpassen.

Auf einem Raspberry Pi ist die Performance zur Nutzung des Features recht begrenzt, flüssig läuft es auf besserer Hardware.

Falls du weitere Frage hast gerne hier:
https://t.me/PhotoboothGroup

Schönes Festtage!
