### ISSUE TITLE
mobile Download Button in Gallery funktioniert nicht

### ISSUE THREAD

**Issue by HappySeppel** [andreknieriem/photobooth#299]
Hi,
wenn ich die Gallery als Standalone über das Handy  aufrufe bekomme ich beim Download der Bilder nur die Thumbs heruntergeladen aber nicht die eigentlichen "orginalen" Bilder. Rufe ich die Website über ein Notebook auf funktioniert der Download, wie kann ich das Problem lösen?
![image](https://user-images.githubusercontent.com/78165321/147649968-eecfda7f-d1bc-4d90-ac22-4c0e24f0eb40.png)

Vielen Dank im Voraus

**Comment by andi34** [comment]
Problem deines Browsers?
Je nach Photobooth--Version ist es eine Option im Adminpanel ( v2.10.0 und neuer).

**Comment by HappySeppel** [comment]
Hi,
ich habe sowohl Firefox als auch Chrome ausprobiert, jedes mal das gleiche.
Current version: 2.1.0
Welche Option meinst du im Admin Panel?

**Comment by andi34** [comment]
Dann ist deine Version zu alt. Wie gesagt ab v2.10.0 lässt sich einstellen ob thumbails beim Download verwendet werden sollen oder nicht.

![Screenshot_20211225-204649](https://user-images.githubusercontent.com/6080900/147657962-a8d5e467-e3a8-444e-b8a5-da18a8b234a1.png)


Dann hakt es bei dir in der Linkerstellung irgendwo, vermutlich hier:
https://github.com/andreknieriem/photobooth/blob/13e779d367f8c7937ca7289120e078594b8a53ae/resources/js/photoinit.js#L123-L130

**Comment by HappySeppel** [comment]
Danke für deine Unterstützung. Ich habe in der download.api eine Zeile eingefügt welche mit per regex die fehlerhafte "thumbs" Erweiterung entfernt.
Da ich den Code etwas angepasst habe für meine Gallery Only Funktion, kann ich nicht ohne weiteres auf die höhere Version springen. Aber ich werde es bei Gelegenheit probieren.

**Comment by HappySeppel** [comment]
Hi ich muss nochmal kurz stören. Du hast geschrieben Version 2.10 ist verfügbar, ich sehe nur die Version 2.1.0 siehe Screenshot. 
![image](https://user-images.githubusercontent.com/78165321/147660526-8ae9e53a-e7c4-46b0-9ba9-2c06b3f323cf.png)

**Comment by andi34** [comment]
https://github.com/andi34/photobooth/releases
