### ISSUE TITLE
WLAN shelly Button - URL for taking photos

### ISSUE THREAD

**Issue by Aquaerics** [andreknieriem/photobooth#301]
I want to use the shelly button (with WLAN connection) to trigger a photo.
https://shelly.cloud/products/shelly-button-1-smart-home-automation-device/

The shelly button can make on a button press a http request like http.//localhost/takephoto.php

It should be the easysiest solution without connectiing a extra button to the raspberry pi i'm using and can be used with other webservers on windows as well. It can be easy konfigured over a internal webpage that is active on start when you connect your new button to usb power.

I checked the php code. but i don't know how to get this realised. Normaly i use html button that triggers an action that can be used to call a php with parameters. 

Thanks for the great project. :-)

**Comment by andi34** [comment]
Requires Photobooth v4 
https://photoboothproject.github.io/Changelog
