### ISSUE TITLE
No background Images with iOS devices running iOS <15

### ISSUE THREAD

**Issue by talentlos** [andreknieriem/photobooth#304]
Since v2.1.0 iOS Devices with iOS Version <15.1 are not able to display the background image any more.

**Comment by andi34** [comment]
Could you please try latest development version from
https://github.com/andi34/photobooth

If you've still issues please open a bug report with additional information in my fork please.

**Comment by andi34** [comment]
Forgot to mention:
Clean installation required. The installer expects user `pi` with membership of group `pi` on some parts.

**Comment by andi34** [comment]
Fixed since Photobooth v3. Full path needs to be defined instead relative path.
