### ISSUE TITLE
Printer problems Canon selphy 

### ISSUE THREAD

**Issue by tincs2** [andreknieriem/photobooth#310]
Hy, 
my i have a problem with my Canon CP800 i can print a test site vrom CUPS i can Print a Text File but i cant print from Photobooth.
the printer worms up and pulls a paper true but nothing more, then i have to unplug and replug the USB the printer gives the paper unprinted out.
when i diconect the printer and rint a image from Photobooth, then plug in the printer and restart the job everything is good the Canon Selphy dos all colors and the print is good.
 
dos anyone have the same isue 

sorrry for my englisch.

best 
Johannes

**Comment by andi34** [comment]
Hey!

You can try updating your printer drivers:
https://www.peachyphotos.com/blog/stories/building-modern-gutenprint/

Also make sure permissions are fine for the Webserver User:
```
sudo gpasswd -a www-data lp
sudo gpasswd -a www-data lpadmin
```

Photobooth executes a command to start the print via command line and appends the image path and name, so this isn't an Photobooth issue itself.
