### ISSUE TITLE
Autofocus on Pentax K-5 II is not working

### ISSUE THREAD

**Issue by greenie67** [andreknieriem/photobooth#311]
My camera (Pentax K-5 II) is not auto focussing. How can I enable autofocus or is it not available for this camera? On the camera itself the autofocus is enabled.

Everything else works fine for me.

Thanks for your help

**Comment by andi34** [comment]
Hey!
I think this is the wrong place to ask. For some cameras the autofocus can be controlled, but it's an option of gphoto2 and not of Photobooth.

Places to look at:
http://gphoto.org/doc/

https://github.com/gphoto/gphoto2

https://github.com/gphoto/libgphoto2
