### ISSUE TITLE
Pyhton 2 requirement

### ISSUE THREAD

**Issue by damanti-me** [andreknieriem/photobooth#312]
**Describe the bug**
First of all - thanks for your work! 
I noticed a missing dependency during the usage of your shell script to install on raspbian. The new OS there would be "Raspberry Pi OS". This OS doesnt include Python2 which is necassary during your installation script. 
Maybe not that urgent.

**To Reproduce**
1. Get a RBP 4
2. fresh RaspberyPIOS lite
3. carry out your shell script

**Expected behavior**
script should run through

**Screenshots**

**Environment (please complete the following information):**
 - OS: Raspberry Pi OS
 - Browser -
 - Version latest

**Photobooth**
- Did it work before? yes
- Which version of Photobooth are you using? latest

**Error log**
`error /var/www/html/node_modules/node-sass: Command failed.`
`gyp verb check python checking for Python executable "python2" in the PATH  `

**Comment by andi34** [comment]
The project is continued here:
https://photoboothproject.github.io/
