### ISSUE TITLE
Raspberry Pi Camera spiegelt statt Horizontal Vertikal

### ISSUE THREAD

**Issue by CPFXDF** [andreknieriem/photobooth#313]
Ich habe die Pi Camera um 180° verdreht eingebaut.
Wenn ich im Admin bereich auf Horizontal spiegeln einstelle, spiegelt sie Vertikal.

Weiß jemand Rat?

**Comment by andi34** [comment]
https://photoboothproject.github.io/

Installier die aktuelle Version.

**Comment by CPFXDF** [comment]
Dankeschön Andi, funktioniert jetzt.
