### ISSUE TITLE
Bild wird nicht gespeichert 

### ISSUE THREAD

**Issue by TheSlowlySnail** [andreknieriem/photobooth#316]
Something went wrong.

Das kommt wenn ich nach der Installation der Version 4 ein Foto aufnehmen will. Auslösen klappt. Es erscheint der besagte Fehler capture and download funktioniert im terminal einwandfrei. Die Ordner wie Image finde ich im terminal navigieren nicht. Mach ich was falsch? Es ist ne canon eos 200 D und über die Konsole tuts.

**Comment by andi34** [comment]
Hey und guten Morgen!
Photobooth ist hier auf v2.1.0 stehen geblieben und wird unter https://github.com/PhotoboothProject/photobooth weiterentwickelt 

Schau gerne Mal im Debugpanel (erreichbar aus dem Adminpanel) ins Photobooth log, dort siehst du die genaue Fehlermeldung welche bei der Problembehandlung hilft.

Grundsätzliche Problemlösungen: https://gist.github.com/andi34/9ef2de10e40c1e556f652b37eb49ba14

Sollte weitere Hilfe benötigt werden gerne in unserer Telegram-Gruppe nachfragen: https://t.me/PhotoboothGroup

Die Foto-Ordner der Photobooth findest du unter /var/www/html/data (Berechtigungen hat dort der www-data Nutzer, ansonsten nur mit root-Rechten).

Da es sich um kein generelles Photobooth-Problem und auch um das falsche Repo handelt schließe ich das Issue.

Viele Grüße

Andi
