### ISSUE TITLE
Dropdown field for frame selection?

### ISSUE THREAD

**Issue by mcbo007** [andreknieriem/photobooth#318]
Hello,

Thanks for the great project!
Is it possible in the backend the frame selection for collections
to design as a dropdown field?

**Comment by andi34** [comment]
The project is continued here:
https://github.com/PhotoboothProject/photobooth

A frame selection might be possible in future, I am working on it but currently other improvements have to be done.

Here's what we've got so far:
https://github.com/PhotoboothProject/photobooth/commit/4dbbdc2256aa5ea27c29d35b8d1e6cefbf09b74b

It's a wip implementation to the live Chroma feature for now.
