### ISSUE TITLE
Kamera löst nicht aus

### ISSUE THREAD

**Issue by sburger83** [andreknieriem/photobooth#32]
Hallo,
Ich benutze einen RaspberryPI 3 und eine Canon DSLR.
Bei klick auf neues Bild wird die Kamera nicht ausgelöst. Steuere ich die Kamera direkt über gphoto an macht sie ein Bild.
wo soll ich nach dem Fehle suchen?

**Comment by F4bsi** [comment]
Hey,
Kann es sein dass du den Developer Modus in den Einstellungen noch an hast?
Bei mir funktioniert es ohne Probleme mit einer Canon DSLR...

**Comment by sburger83** [comment]
Wo kann ich den denn ausschalten? Leider funktioniert die Seite mit dem Tutorial nicht, ansonsten hätte ich da nachgeschaut.

**Comment by F4bsi** [comment]
In der config.inc.php Datei im Hauptverzeichnis musst du die Zeile $config['dev'] = true zu $config['dev'] = false ändern. Denn sollte es funktionieren

**Comment by soko1988** [comment]
@sburger83 Das Tutorial ist gut beschrieben. Da steht auch ganz deutlich, dass man den DEVELOPER Modus deaktivieren soll.

**Comment by andreknieriem** [comment]
Hey die Seite läuft wieder. Es gab einen Fehler im Firefox Browser mit einem JS.
https://www.andrerinas.de/tutorials/raspberry-pi-einen-dslr-weddingphotobooth-erstellen.html
