### ISSUE TITLE
Bug im homebtn

### ISSUE THREAD

**Issue by talentlos** [andreknieriem/photobooth#37]
Der Link für den Homebutton in der index.php in Zeile 61 spart das Icon und den Text aus. Man muss also den Button am Rand erwischen, sonst geht er nicht. Ich konnte den Fehler leider nicht nachvollziehen und habe mir damit beholfen, einen Reload einzubauen:

aus

`<a href="#" class="btn homebtn"> <i class="fa fa-home" href="#"></i> <span data-l10n="home"></span></a>`
     

wird

  `<a href="#" onclick="window.location.reload(true);" class="btn homebtn"> <i class="fa fa-home" href="#"></i> <span data-l10n="home"></span></a>`

dann geht es...

**Comment by andreknieriem** [comment]
Danke. Werde ich reparieren.

**Comment by andreknieriem** [comment]
Behoben
