### ISSUE TITLE
Feature Request - Protection of the Admin Page

### ISSUE THREAD

**Issue by TKnpl** [andreknieriem/photobooth#39]
Hallo Andre,
vielen Dank, dass du dieses coole Projekt der Öffentlichkeit zur Verfügung stellst!
Zu deinem neuesten Release 1.5.0 habe ich eine Anmerkung bzw. einen Verbesserungsvorschlag.
Derzeit ist die Admin Seite von jedem aufrufbar und die Inhalte manipulierbar, der diese Seite kennt.
Da bei der Download Option via. QR Code bereits die Base URL ersichtlich ist, kann ich mir vorstellen, dass die Admin Seite recht schnell gefunden werden kann.
Daher würde ich mir wünschen, dass die Admin Seite in der Konfig deaktivierbar ist und/oder bei Aufruf der Seite eine Passworteingabe erfolgen muss, sodass nicht jeder die Inhalte ändern kann.
Vielen Dank und viele Grüße

**Comment by Seppel0815** [comment]
Eine Idee: 

Erstell doch eine .htaccess in dem Unterordner /Admin 



Lg

**Comment by andreknieriem** [comment]
Ja das würde ich auch empfehlen, wenn du denkst, dass jemand die Admin Page suchen könnte. Das Photobooth ist ja eigentlich nicht via Internet erreichbar und dann müsste es schon jemand der Gäste sein. 
Evtl. erstelle ich noch eine .htaccess als Demo Datei in dem Ordner, die man benutzen kann, oder nicht.

https://tools.andrerinas.de/htpasswd_generator

**Comment by andi34** [comment]
Reopen: https://github.com/andreknieriem/photobooth/pull/118
