### ISSUE TITLE
Admin: Bild-Ordner können geändert werden - Bilder werden aber nicht angezeigt

### ISSUE THREAD

**Issue by Norman-Sch** [andreknieriem/photobooth#41]
Wenn ich auf der Adminseite z.B. den Bild-Ordner nach /home/photobooth/images ändere dann werden die Bilder dort zwar abgespeichert aber weder auf der Home-Seite, noch in der Gallery angezeigt.

**Comment by andreknieriem** [comment]
Ok werde ich mir ansehen.

**Comment by andreknieriem** [comment]
Ich habe es erst einmal behoben. Allerdings geht das Ganze nur für Pfade ohne / vorne. Also images, aber nicht /photobooth/images, da das Javascript sonst nicht weiß, wo er gucken soll. Ich werde mal sehen, wie man das verbessert

**Comment by Norman-Sch** [comment]
Das wäre super. Ich nutze ein Netbook mit Xubuntu 16.04 und möchte ungern die Systempartition mit Bildern füllen. Vielen Dank für deine Bemühungen!

**Comment by andi34** [comment]
Symlink?

**Comment by andi34** [comment]
cd /var/www/html
rm -rf pictures
ln -s /home/photobooth/images ./pictures

**Comment by andi34** [comment]
Geklappt?
