### ISSUE TITLE
Feature request: print confirmation

### ISSUE THREAD

**Issue by thymon13** [andreknieriem/photobooth#44]
Hi,

Is it possible to confirm with pop up or other when I click on print button ?
Currently nothing happens on the screen when you click on it. And people by reflex reclick several times over.

Sorry for my English :)

Thanks in advance.

thymon

**Comment by thymon13** [comment]
Some help ?

**Comment by tobiasHaecker** [comment]
Hallo André,
ich habe das so in die aktuelle Version eingebaut, funktioniert aber leider nicht.
Kannst du mir noch einen Tipp geben, was ich vergessen habe?
Vielen Dank.

**Comment by andi34** [comment]
Doofe Frage: ```$config['print']['msg'] = '';```
Ist das schon implementiert nur eben keine Rückmeldung, da kein Text?
@tobiasHaecker kannst du Mal schauen ob es reicht
```$config['print']['msg'] = 'Druckauftrag gesendet....';

**Comment by ChrisKram** [comment]
Im Admin Panel lässt sich ein Text eintragen, jedoch wird er nicht angezeigt. 

 @andi34, beziehst du dich mit dem Versuch auf die my.config.inc.php?
Bei mir wird die Datei nicht geändert. Ich habe nur die json Datei im Admin Folder, welche die Einstellungen enthält.

**Comment by andi34** [comment]
Kannst du auch im Admin Panel eingeben in dem Fall.

**Comment by andi34** [comment]
discussion/development continues here https://github.com/andreknieriem/photobooth/issues/68
