### ISSUE TITLE
Greenwall-Funktion 

### ISSUE THREAD

**Issue by obkram** [andreknieriem/photobooth#59]
Entschuldigt wenn ich wegen einer Funktionsanfrage einen issue aufmache, aber hat sich schon Mal jemand über eine Greenwall Funktion für den Photobooth Gedanken gemacht? Wäre sicherlich ein nettes Feature.

LG Sven O.

**Comment by andi34** [comment]
https://github.com/andreknieriem/photobooth/issues/26

**Comment by obkram** [comment]
Danke Andreas, der ist mir wohl durchgegangen, das tut mir leid.
Das Ticket wird hiermit geschlossen.

LG Sven
