### ISSUE TITLE
Auslösen per Taster

### ISSUE THREAD

**Issue by BJunik** [andreknieriem/photobooth#62]
Wäre es möglich die Funktionen wie Foto erstellen, Gallery öffnen auf GPIO´s zu legen und den Status dieser abzufragen? So könnte ein Bildschirm ohne Touch eingesetzt werden.

**Comment by andi34** [comment]
Duplicate: https://github.com/andreknieriem/photobooth/issues/10

Aber schau Mal hier:
https://github.com/andreknieriem/photobooth/pull/58

Kann natürlich entsprechend der eigenen Wünsche erweitert werden.
