### ISSUE TITLE
Feature request: FTP Upload

### ISSUE THREAD

**Issue by BJunik** [andreknieriem/photobooth#63]
Weiterhin wäre eine Upload Funktion per FTP eine tolle Funktion.
Den QR Code könnte man anders verlinken und der User könnte sich sein Bild direkt vom Webserver abrufen.

**Comment by andi34** [comment]
localhost/images

"localhost" kann natürlich durch die IP des Pi ersetzt werden.

**Comment by andi34** [comment]
Keine Rückmeldung erhalten.
