### ISSUE TITLE
Feature request: Eigene Rahmen, Text oder Logos für den Fotodruck

### ISSUE THREAD

**Issue by ChrisKram** [andreknieriem/photobooth#67]
Neben dem barcode wäre eine Möglichkeit eigene Daten oder Rahmen mit zu drucken eine tolle Option. 

So kann bei einer Hochzeit bspw. das Datum, die Namen, Ort, etc. mit gedruckt werden. Weiterhin könne man einen eigenen Rahmen, der die Veranstaltung beschreibt oder einen Anlass, z.B. ein Mistelzweig zu Weihnachten ect. erlauben oder Logos mit Drucken. 

Ein Rahmen kann auch ein Hintergrund sein, der unter das Foto gelegt wird und so das skalierte Bild umschließt. 

Ein Chroma Keying ist dafür nicht zwingend erforderlich.

**Comment by andi34** [comment]
On my list:
https://github.com/andi34/photobooth/issues/22

**Comment by andi34** [comment]
https://github.com/andreknieriem/photobooth/issues/9

**Comment by andi34** [comment]
![deb800943fb1e89d31da5c8bf0660267](https://user-images.githubusercontent.com/6080900/64485719-2b61dc00-d224-11e9-9478-88409e7bbae3.jpg)

**Comment by andi34** [comment]
frame.png needs to be added to root of photobooth.
https://github.com/andi34/photobooth/commit/20a9b16623431942aed1610e843ae6f2e665366b#diff-d5fde551bb3c77d93baa17a8ba21e781R58

If someone can share a frame which can be used in this project without license issues let me know.
No frame.png added by default until that.

**Comment by andi34** [comment]
added example frame

![affa4b9397dfd454c3cd5939265cd154](https://user-images.githubusercontent.com/6080900/64486345-39b3f600-d22c-11e9-96e6-42a1e2704daa.jpg)

**Comment by tobiashaas** [comment]
Ich hab dir ne Mail mit einem Frame geschickt!

**Comment by andi34** [comment]
Danke :)
Hast schon getestet damit?
Bin grad nur mobil, müsste heute Abend am PC dann schauen.

**Comment by tobiashaas** [comment]
Leider noch nicht... Hab grade meinen Raspi nicht zur Hand ...

**Comment by andi34** [comment]
Ok, links und rechts ist noch Teil vom Bild Eigentlich, somit sollte dein Rahmen nicht abschließen am Rand . Muss Mal schauen wie ich das behoben bekomme dann.
Aber bekommen wir hin :)

**Comment by andi34** [comment]
discussion/development continues here https://github.com/andreknieriem/photobooth/issues/68
