### ISSUE TITLE
Create a FAQ

### ISSUE THREAD

**Issue by andi34** [andreknieriem/photobooth#69]
## Collection of questions to create a proper FAQ
You noticed there's the same question again in the comments? Please let us know in the comments below if we haven't noticed it already.

[MOVED TO WIKI ALREADY](https://github.com/andreknieriem/photobooth/wiki)

**Comment by sualko** [comment]
Can you move this to the wiki, so that everyone can change, update or add stuff?

**Comment by andi34** [comment]
Sure, that was the goal. this issue was only used as a starting point to collect stuff first.

**Comment by andi34** [comment]
Everything moved to Wiki.
Everyone can feel free to update pages or add more questions and answers.

Next step will be to move the installation instructions out of the README and add pages for every supported platform (Win,Linux,Mac).

**Comment by andi34** [comment]
Installation instructions from README moved to Wiki

**Comment by sualko** [comment]
Why did you create a new page for every question? In my opinion it's clearer and more common to have every faq on one page. If you don't mind, I would delete all those pages and put them on one.

**Comment by andi34** [comment]
Feel free to optimize it. Thought it's cleaner this way.
