### ISSUE TITLE
Feature request: Download directly from gallery and password

### ISSUE THREAD

**Issue by vrs01** [andreknieriem/photobooth#7]
Hi!

Instead of using the qr codes for downloading images I would like to download the images directly from gallery view by clicking on them. Since everybody needs to be connected to the photo booth Wi-Fi anyway, I think it is more convenient than the qr codes. One could implement also a password into the photo booth page so that without password, people can download images and the password is only entered on the tablet that is used for taking photos. One could even think of loading the photo booth page like a landing page right after connecting to the WiFi.

Best, vrs01

**Comment by andi34** [comment]
+1 on downloading images directly from gallery.
Isn't it prepared already by the download.php?

**Comment by andi34** [comment]
discussion/development continues here https://github.com/andreknieriem/photobooth/issues/68

**Comment by andi34** [comment]
Reopen and close collection thread
