### ISSUE TITLE
Bug: Collage Sometimes not created

### ISSUE THREAD

**Issue by andi34** [andreknieriem/photobooth#72]
Mentioned in Andrés Webpage.

Idea to solve this problem:
Adjust the busy time, make if configurable:

https://github.com/andreknieriem/photobooth/blob/master/resources/js/core.js#L137

Trying a higher value might solve the problem.

**Comment by flighter18** [comment]
While I was implementing the collage function I had some trubles with PHP max_execution_time?
I didn't have any problem last weekend during the wedding.

**Comment by andi34** [comment]
@flighter18 like this as ```/var/www/html/php.ini``` ?

```
[PHP]
max_execution_time = 60
max_input_time = 60
memory_limit = 128M
```

**Comment by andi34** [comment]
forget it, found it: https://github.com/andreknieriem/photobooth/commit/8fa282d3cf93d0e6b56e5c77b50f5452437744dd

open http://localhost/phpinfo.php

take a look for "Loaded Configuration File", you need  sudo rights to edit the file.
Page will look like this:

![Screenshot_2019-09-20_10-07-41](https://user-images.githubusercontent.com/6080900/65310524-cd6fb580-db8e-11e9-86e4-26b41a0bac8c.png)
