### ISSUE TITLE
Bug v1.9.0: fonts size needs adjustment

### ISSUE THREAD

**Issue by thymon13** [andreknieriem/photobooth#84]
Hi,

Is it possible to adjust the Fonts size ?

![IMG_0639](https://user-images.githubusercontent.com/18228022/65821095-5d69cb00-e231-11e9-9c6d-08e7e9a7718f.jpg)

**Comment by andi34** [comment]
What's your resolution?

**Comment by thymon13** [comment]
Responsive does not adapt the font size automatically?
1280x800

**Comment by andi34** [comment]
For now you could adjust the font-size inside the style.css (https://github.com/andreknieriem/photobooth/blob/master/resources/css/style.css#L60)
```
h1 {
  font-size: 50px;
  margin: 33px 0; }
```
Try something below 50px.

**Comment by andi34** [comment]
@sualko could you take a look at it?

**Comment by thymon13** [comment]
same in MacBook with Google Chrome
<img width="1438" alt="Capture d’écran 2019-09-30 à 20 15 51" src="https://user-images.githubusercontent.com/18228022/65904812-7bfdcc80-e3bf-11e9-97b0-230ee675f9e2.png">

**Comment by sualko** [comment]
Please download my fix from https://github.com/sualko/photobooth/tree/fix/start-layout and report if it fixes your issue.
