### ISSUE TITLE
Feature request: Text overlay for photo printing

### ISSUE THREAD

**Issue by vrs01** [andreknieriem/photobooth#9]
It would be nice to overlay one line of text maybe at the bottom of the printed fotos. Like the title of the event and the date ("Wedding of XY and YX, 1st of April 1916").

**Comment by Seppel0815** [comment]
Look at imagemagick, you can edit the php Files (i have insert a overlay Watermark with imagemagick)

**Comment by jensfr1** [comment]
> Can you share the example?

**Comment by thymon13** [comment]
Yes I need too :)

**Comment by vdubuk** [comment]
file   print.php   uses GD to merge the Photo and QR code

GD has a function to add text to an image   imagefttext     

I am a newbie with php but am going to  try to use GD imagefttext  as it is already used in print.php

**Comment by vdubuk** [comment]
Very rough test.  in file print.php  after 

`imagecopyresized($print, $code, $width, 0, 0, 0, ($height / 2), ($height / 2), imagesx($code), imagesy($code));`

add the following 
`// text on print - ensure you include path to your font
imagettftext ($print, 30, 0, 850, 350, $black, 'resources/fonts/GreatVibes-Regular.ttf' , 'Line 1 text' );
imagettftext ($print, 30, 0, 850, 450, $black, 'resources/fonts/GreatVibes-Regular.ttf' , 'Line 2 text' );`

**Comment by vdubuk** [comment]
My next step is to try and add options to the admin panel to allow for easier change of text, font, size etc..

**Comment by andi34** [comment]
Thanks. Let me know if you have something ready, else I might be able to look at it at some point this week.

**Comment by andi34** [comment]
discussion/development continues here https://github.com/andreknieriem/photobooth/issues/68
