### ISSUE TITLE
Probleme mit Chroma Keying nach Fotoerstellung

### ISSUE THREAD

**Issue by obkram** [andreknieriem/photobooth#91]
Mir ist folgendes aufgefallen. Hat man ein Foto aufgenommen dann bekommt man dieses nach der Aufnahme angezeigt. Wenn man aus dieser Ebene auf den Button Gallerie klickt, das gerade aufgenommene Bild wählt und dann von dort aus Chroma Keying ( also das Pinselsymbol ) auswählt dann bekommt man die Meldung...
Chroma Keying nicht möglich!
Darunter befindet sich ein Schließen Button. Dieser ist allerdings 15-20 Sekunden inaktiv und die Meldung bleibt so lange stehen bis man dann nach 20 Sekunden den Button drückt.

Geht man allerdings unmittelbar nach der Bildaufnahme via Home Button zurück ins Hauptmenü und wählt von dort aus die Galerie, das letzte Foto und dann Chroma Keying dann funktioniert es direkt.

**Comment by andi34** [comment]
@obkram ist mir auch aufgefallen, hatte noch keine Zeit mir das anzuschauen.

**Comment by obkram** [comment]
@sualko : in my case it works fine, thank you
@andi34 : in diesem Zusammenhang ist mir aufgefallen das das erste Bild ins leere läuft. Soll heißen es wird nicht als Bild gewertet und kann auch nicht selektiert werden. Das funktioniert dann erst wenn zwei Bilder in der Gallerie sind.
![grafik](https://user-images.githubusercontent.com/33160929/65948496-aa6cbd80-e43a-11e9-96bf-2aa5450e3d16.png)

**Comment by sualko** [comment]
@obkram I fixed your second issue also the pr. Please give it another try.

**Comment by obkram** [comment]
@sualko : I tested it, works fine too.

**Comment by obkram** [comment]
@sualko : i know that this is the wrong ticket but we have a nice run ;-).
Do the picturefilter **blur** and **selective blur** have any effect on your system?

**Comment by andi34** [comment]
@obkram seems like the blur of GD isn't that effective.
https://stackoverflow.com/questions/7245710/php-gd-better-gaussian-blur
https://stackoverflow.com/questions/14428257/how-to-achieve-a-blur-effect-in-php

We would need to use a different setup for the blur to be not that weak.
