### ISSUE TITLE
reset mailaddresses.txt via resetbutton

### ISSUE THREAD

**Issue by obkram** [andreknieriem/photobooth#95]
Wäre es machbar das Löschen des Inhalts der mailaddresses.txt mit dem Zurücksetzen Button zu verbinden?

**Comment by obkram** [comment]
sorry, that doesen´t work. I can see that the data.txt will be removed when i click on the reset button but the mail-addresses.txt will still exist.

**Comment by sualko** [comment]
Do you have any errors in your apache log? Which permission has `mailaddresses.txt`? Easiest way is to execute `ls -l mailaddresses.txt ` in your root folder.

**Comment by obkram** [comment]
@sualko : sorry, i copied the lines to the Wrong position. Now it works fine. Thanks.
Should i close the ticket?

**Comment by sualko** [comment]
Please leave it open. If the pr is merged, it's closed automatically and marked as resolved by that pr.
